### ISSUE TITLE
malloc freed pointer error

### ISSUE THREAD

**Issue by celic** [smuellerDD/acvpproxy#11]
I ended up with this output during a run today. Not entirely sure what caused it (perhaps flakey internet). Thoughts?

```
ACVPProxy (16:57:53) Status: (Re)Try testID 14183 / vsID 39698 (132 / 534 done)
ACVPProxy (16:57:55) Status: (Re)Try testID 14184 / vsID 39706 (132 / 534 done)
acvp-proxy(5157,0x700007328000) malloc: *** error for object 0x7f91b3063d10: pointer being freed was not allocated
acvp-proxy(5157,0x700007328000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Run using `./acvp-proxy -m OpenSSL -f --request -v`

**Comment by smuellerDD** [comment]
Am Freitag, 17. Mai 2019, 02:01:23 CEST schrieb Chris Celi:

Hi Chris,

> I ended up with this output during a run today. Not entirely sure what
> caused it (perhaps flakey internet). Thoughts?
> 
> ```
> ACVPProxy (16:57:53) Status: (Re)Try testID 14183 / vsID 39698 (132 / 534
> done) ACVPProxy (16:57:55) Status: (Re)Try testID 14184 / vsID 39706 (132 /
> 534 done) acvp-proxy(5157,0x700007328000) malloc: *** error for object
> 0x7f91b3063d10: pointer being freed was not allocated
> acvp-proxy(5157,0x700007328000) malloc: *** set a breakpoint in
> malloc_error_break to debug Abort trap: 6
> ```
> 
> Run using `./acvp-proxy -m OpenSSL -f --request -v`

This is very likely the OpenSSL issue specified in README.openssl.md - somehow 
the code to counter the issue is not fully applied. May I come and see you 
tomorrow for the compilation steps?

Ciao
Stephan

**Comment by celic** [comment]
I have not seen this error since it happened and have had no issues with the client. I'll go ahead and close this out and chalk it up to newbie errors :)
