### ISSUE TITLE
Spurious Error

### ISSUE THREAD

**Issue by celic** [smuellerDD/acvpproxy#13]
I have seen this error once before, and I'd just like to run it by you to make sure it isn't a known problem with the client. I'm still trying to figure out if it is an issue with our server instead.

The client seemingly stops receiving messages back from the server but continues on consuming massive amounts of CPU (over 700% of my available resources!). 

Here is some output to show what I mean. 

```
ACVPProxy (12:43:05) Status: (Re)Try testID 5655 / vsID 7561 (71 / 297 done)
ACVPProxy (12:43:11) Status: (Re)Try testID 5645 / vsID 7410 (71 / 297 done)
ACVPProxy (12:43:11) Status: (Re)Try testID 5655 / vsID 7562 (71 / 297 done)
ACVPProxy (12:43:12) Status: Logging into ACVP server
ACVPProxy (12:43:13) Status: (Re)Try testID 5650 / vsID 7456 (71 / 297 done)
ACVPProxy (12:43:42) Status: Logging into ACVP server
ACVPProxy (12:44:12) Status: Logging into ACVP server
ACVPProxy (12:44:42) Status: Logging into ACVP server
```

The client is processing as usual at first, then at some point just ends up trying to log in to the ACVP server (which I assume is just refreshing the JWT) with no other content. As far as I can tell, the server is still responsive to incoming messages from a different instance of a client. 

Thoughts?

**Comment by smuellerDD** [comment]
Am Mittwoch, 22. Mai 2019, 19:04:58 CEST schrieb Chris Celi:

Hi Chris,

> Thoughts?

No thoughts so far. I still attribute it to the anticipated OpenSSL issue. My 
colleages as well as myself use a Mac and have not seen this. I will start 
stressing my macs now.

Thanks for the reports!

Ciao
Stephan

**Comment by smuellerDD** [comment]
Closing - to my impression, this relates to issue #12.
