### ISSUE TITLE
--request for vector returns nothing

### ISSUE THREAD

**Issue by surajshardade** [smuellerDD/acvpproxy#15]
Hi,

I have created acvpproxy_conf.json and updated all information. when I tried "./acvp_proxy -l" it ran successfully and returning all crypto module supported, but when I made a request for test vectors it is not returning anything.
could you please help me with this?

![ACVP_proxy](https://user-images.githubusercontent.com/43987488/84002306-54ceb480-a9bc-11ea-80ca-a7269f0dbdab.PNG)

**Comment by smuellerDD** [comment]
Am Montag, 8. Juni 2020, 09:15:28 CEST schrieb surajshardade:

Hi surajshardade,

> Hi,
> 
> I have created acvpproxy_conf.json and updated all information. when I tried
> "./acvp_proxy -l" it ran successfully and returning all crypto module
> supported, but when I made a request for test vectors it is not returning
> anything. could you please help me with this?
> 
> ![ACVP_proxy](https://user-images.githubusercontent.com/43987488/84002306-54
> ceb480-a9bc-11ea-80ca-a7269f0dbdab.PNG)

Reinvoke the command with -v and have a look if there are warnings. If you do 
not find anything, use -vvv with debug messages to check what the proxy has a 
problem with.

Ciao
Stephan

**Comment by surajshardade** [comment]
Hi Stephan,

Thanks for your quick reply. 
when I ran --request cmd with -v option it is showing below error: 
_ACVPProxy (01:29:44) (acvp-proxy) Warning - TOTP MQ System: Server: cannot create message queue (-38)_
could you please guide me to resolve this issue?

**Comment by surajshardade** [comment]
Thanks, Stephan :). I will look into it.

**Comment by surajshardade** [comment]
Hi Stephan ,

It went further, but now seeing "_No cipher implementation found for search criteria_" issue.
![proxy_no_cipher_implementation](https://user-images.githubusercontent.com/43987488/84033298-c0c91100-a9ec-11ea-8e68-917a239a390a.PNG)
the same issue is occurring for "acvp-proxy -l" cmd . can you please help?

**Comment by smuellerDD** [comment]
Am Montag, 8. Juni 2020, 15:04:29 CEST schrieb surajshardade:

Hi surajshardade,

> Hi Stephan ,
> 
> It went further, but now seeing "_No cipher implementation found for search
> criteria_" issue.
> ![proxy_no_cipher_implementation](https://user-images.githubusercontent.com
> /43987488/84033298-c0c91100-a9ec-11ea-8e68-917a239a390a.PNG) the same issue
> is occurring for "acvp-proxy -l" cmd . can you please help?

There can be several issues: either you compiled the proxy with extensions 
(make extensions) and you did not specify --proxy-extension-dir pointing to 
your directory with extensions - check that -u lists something.

If -u lists something, you may not have a module_definitions directory 
containing the instantiation information required for your uninstantiated 
module definition (see README.md for details how the JSON configs link to the 
C code or use the upstream module_definition).


Ciao
Stephan
