### ISSUE TITLE
acvpproxy expired jwt authtoken issue

### ISSUE THREAD

**Issue by davecornwell** [smuellerDD/acvpproxy#16]
I am trying to verify some PROD vectors for testid 1906 with vectors sets 21494 and 21495..

Here is the error messages I get

ACVPProxy (17:48:35) (vid21495) Error: Received following ACVP server error response: [{"acvVersion":"1.0"},{"error":"The provided JWT expired at 2020-07-23 00:36:33Z and is no longer valid. The JWT claims may be refreshed through the renewal process described in the specification."}]
ACVPProxy (17:48:35) (vid21495) Error: Failure to submit testID 1906 with vsID 21495
ACVPProxy (17:48:35) (vid21494) Error: Received following ACVP server error response: [{"acvVersion":"1.0"},{"error":"The provided JWT expired at 2020-07-23 00:36:33Z and is no longer valid. The JWT claims may be refreshed through the renewal process described in the specification."}]
ACVPProxy (17:48:35) (vid21494) Error: Failure to submit testID 1906 with vsID 21494

Is this a bug or is there a way to refresh the jwtauthtoken?

thank you
David Cornwell
cornwell_david@bah.com

**Comment by smuellerDD** [comment]
The version 1.5.0 has the support for automatic refresh - which version do you use?

**Comment by davecornwell** [comment]
Thanks Stephan,

An older version. I will update it.

Thank you
Dave

**Comment by smuellerDD** [comment]
Issue seems closed with update. Please reopen if it is still an issue
