### ISSUE TITLE
Error 403 on --publish

### ISSUE THREAD

**Issue by tomstom** [smuellerDD/acvpproxy#17]
Hello Stephan,

I try for several days to publish a testsession. I’m using the version 1.5.1

For example, the http_request of the folder "testsessions" list all testsessions, and the session I want to publish is marked as publishable=true and passed=true. So everything looks great.

But if I call –publish, the proxy stops with error 403 in the function acvp_publish_ready(testid_ctx), if I deactivate this check in the “acvp_publish_testid()” I get the same error for the following call “acvp_publish_request(testid_ctx, json_publish)”. Therefore, it seems that I have no access rights to do a http_post or a http_put on testSession/ID/ in the function “acvp_publish_testid”. I also checked the url with the debugger and it is targeting to the right testSessionID. I hope you can help me.

Thank you,
Thomas Klocke

Log:
ACVPProxy (12:04:08) (acvp-proxy) Status: Publishing testID XXXXX
ACVPProxy (12:04:08) (acvp-proxy) Status: Validating vendor reference XXXXX
ACVPProxy (12:04:09) (acvp-proxy) Status: Validating person reference XXXXX
ACVPProxy (12:04:10) (acvp-proxy) Status: Validating operational environment dependency reference XXXXX
ACVPProxy (12:04:10) (acvp-proxy) Status: Validating operational environment dependency reference XXXXX
ACVPProxy (12:04:11) (acvp-proxy) Status: Validating operational environment reference XXXXX
ACVPProxy (12:04:12) (acvp-proxy) Status: Validating module reference XXXXX
ACVPProxy (12:04:14) (acvp-proxy) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (12:05:20) (acvp-proxy) Status: Logging into ACVP server to refresh existing auth token
ACVPProxy (12:05:21) (acvp-proxy) Error: Failure in processing testID XXXXX with vsID 0 (-403) for module OpenSSL (64 bit) (TDES_C) (TDES_C)
Command invocation returned 22
Module Name                              | Test ID  | Request Type    | ID      

Check the above listing - if request IDs are present, inform NIST to approve them and re-invoke this command.

=========================================

The following certificates were obtained:

Module Name                                        | Test ID  | Certificate No

**Comment by smuellerDD** [comment]
Am Dienstag, 28. Juli 2020, 12:08:30 CEST schrieb tomstom:

Hi tomstom,

> Hello Stephan,
> 
> I try for several days to publish a testsession. I’m using the version
> 1.5.1
 
> For example, the http_request of the folder "testsessions" list all
> testsessions, and the session I want to publish is marked as
> publishable=true and passed=true. So everything looks great.
 
> But if I call –publish, the proxy stops with error 403 in the function
> acvp_publish_ready(testid_ctx), if I deactivate this check in the
> “acvp_publish_testid()” I get the same error for the following call
> “acvp_publish_request(testid_ctx, json_publish)”. Therefore, it seems that
> I have no access rights to do a http_post or a http_put on testSession/ID/
> in the function “acvp_publish_testid”. I also checked the url with the
> debugger and it is targeting to the right testSessionID. I hope you can
> help me.
 
> Thank you,
> Thomas Klocke
> 
> 
> Log:
> ACVPProxy (12:04:08) (acvp-proxy) Status: Publishing testID XXXXX
> ACVPProxy (12:04:08) (acvp-proxy) Status: Validating vendor reference XXXXX
> ACVPProxy (12:04:09) (acvp-proxy) Status: Validating person reference XXXXX
> ACVPProxy (12:04:10) (acvp-proxy) Status: Validating operational
> environment dependency reference XXXXX ACVPProxy (12:04:10) (acvp-proxy)
> Status: Validating operational environment dependency reference XXXXX
> ACVPProxy (12:04:11) (acvp-proxy) Status: Validating operational
> environment reference XXXXX ACVPProxy (12:04:12) (acvp-proxy) Status:
> Validating module reference XXXXX ACVPProxy (12:04:14) (acvp-proxy) Status
> - TOTP MQ System: Requesting OTP value, waiting ... ACVPProxy (12:05:20)
> (acvp-proxy) Status: Logging into ACVP server to refresh existing auth
> token ACVPProxy (12:05:21) (acvp-proxy) Error: Failure in processing testID
> XXXXX with vsID 0 (-403) for module OpenSSL (64 bit) (TDES_C) (TDES_C)
> Command invocation returned 22

This log is not of much help. What you need to tell me is the endpoint you see 
that issue.


Use the same command but add -vvv. Then skim through the logs to find the 
endpoint that returns 403, which looks like:

*  subjectAltName: host "demo.acvts.nist.gov" matched cert's 
"demo.acvts.nist.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> POST /acvp/v1/testSessions HTTP/1.1

The question is why you get 403 - access denied.

> Module Name                              | Test ID  | Request Type    | ID  
>    
 
> Check the above listing - if request IDs are present, inform NIST to approve
> them and re-invoke this command.
 
> =========================================
> 
> The following certificates were obtained:
> 
> Module Name                                        | Test ID  | Certificate
> No
 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/acvpproxy/issues/17


Ciao
Stephan

**Comment by tomstom** [comment]
Good morning,

Ok, here is the part of the log:

ACVPProxy (22:45:55) (acvp-proxy) Verbose: ACVP URL: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
ACVPProxy (22:45:55) (acvp-proxy) Verbose: testID URL: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/12345
ACVPProxy (22:45:55) (acvp-proxy) Verbose: (Re)Try testID 12345
ACVPProxy (22:45:55) (acvp-proxy) Debug: Existing test session JWT access token has sufficient lifetime
ACVPProxy (22:45:55) (acvp-proxy) Debug - HTTP operation: HTTP Authentication header: Authorization: Bearer eyJhbGciOiJIUzI-trunceted_byMe
ACVPProxy (22:45:55) (acvp-proxy) Debug - HTTP operation: Performing an HTTP GET operation
ACVPProxy (22:45:55) (acvp-proxy) Verbose - HTTP operation: TLS peer verification enabled with CA file /home/tom/keys/mozzila_trust_anchors.pem.
ACVPProxy (22:45:55) (acvp-proxy) Debug - HTTP operation: Setting certificate with type PEM
ACVPProxy (22:45:55) (acvp-proxy) Debug - HTTP operation: Setting private key with type PEM
*   Trying 52.204.191.193:443...
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/tom/keys/mozzila_trust_anchors.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Maryland; L=Gaithersburg; O=National Institute of Standards and Technology; OU=STVM ACVP; CN=demo.acvts.nist.gov
*  start date: Jun  1 00:00:00 2020 GMT
*  expire date: Jun 20 12:00:00 2021 GMT
*  subjectAltName: host "demo.acvts.nist.gov" matched cert's "demo.acvts.nist.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /acvp/v1/testSessions/12345 HTTP/1.1
Host: demo.acvts.nist.gov
User-Agent: ACVPProxy/1.5.1
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsIn-truncated_byMe

* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Transfer-Encoding: chunked
< Server: Microsoft-IIS/8.5
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Date: Tue, 28 Jul 2020 20:45:52 GMT
< 
* Connection #0 to host demo.acvts.nist.gov left intact
ACVPProxy (22:45:56) (acvp-proxy) Warning - HTTP operation: Unable to HTTP GET data for URL https://demo.acvts.nist.gov:443/acvp/v1/testSessions/12345: 403
ACVPProxy (22:45:56) (acvp-proxy) Debug - HTTP operation: HTTP return code: 403
ACVPProxy (22:45:56) (acvp-proxy) Verbose - HTTP operation: ACVP server return code: JWT expired
ACVPProxy (22:45:56) (acvp-proxy) Warning: Authentication error received - force refresh of auth token and retry network operation
ACVPProxy (22:45:56) (acvp-proxy) Verbose - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (22:45:56) (acvp-proxy) Verbose - TOTP MQ System: Client: Requesting TOTP value from message queue server
ACVPProxy (22:45:56) (totp0) Verbose - TOTP generation: sleeping for 22 seconds
ACVPProxy (22:46:18) (totp0) Verbose - TOTP MQ System: Server: TOTP value delivered to client
ACVPProxy (22:46:18) (acvp-proxy) Verbose - TOTP MQ System: Client: Received TOTP value from message queue server
ACVPProxy (22:46:18) (acvp-proxy) Verbose: Perform a refresh of the existing JWT access token
ACVPProxy (22:46:18) (acvp-proxy) Verbose: Logging into ACVP server to refresh existing auth token
ACVPProxy (22:46:18) (acvp-proxy) Verbose: ACVP URL: https://demo.acvts.nist.gov:443/acvp/v1/login
ACVPProxy (22:46:18) (acvp-proxy) Debug - HTTP operation: Performing an HTTP POST operation
ACVPProxy (22:46:18) (acvp-proxy) Verbose - HTTP operation: TLS peer verification enabled with CA file /home/tom/keys/mozzila_trust_anchors.pem.
ACVPProxy (22:46:18) (acvp-proxy) Debug - HTTP operation: Setting certificate with type PEM
ACVPProxy (22:46:18) (acvp-proxy) Debug - HTTP operation: Setting private key with type PEM
*   Trying 52.204.191.193:443...
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/tom/keys/mozzila_trust_anchors.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Maryland; L=Gaithersburg; O=National Institute of Standards and Technology; OU=STVM ACVP; CN=demo.acvts.nist.gov
*  start date: Jun  1 00:00:00 2020 GMT
*  expire date: Jun 20 12:00:00 2021 GMT
*  subjectAltName: host "demo.acvts.nist.gov" matched cert's "demo.acvts.nist.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> POST /acvp/v1/login HTTP/1.1
Host: demo.acvts.nist.gov
User-Agent: ACVPProxy/1.5.1
Accept: */*
Content-Type: application/json
Content-Length: 388

* upload completely sent off: 388 out of 388 bytes
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: application/json; charset=utf-8
< Server: Microsoft-IIS/8.5
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Date: Tue, 28 Jul 2020 20:46:15 GMT
< 
* Connection #0 to host demo.acvts.nist.gov left intact
ACVPProxy (22:46:19) (acvp-proxy) Debug: Process following server response for HTTP return code 200: [
  {
    "acvVersion": "1.0"
  },
  {
    "accessToken": "eyJhbGciOiJIUzI-truncated_byMe",
    "largeEndpointRequired": false,
    "sizeConstraint": -1
  }
]
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore/
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore//vendor
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore//vendor/OpenSSL__64_bit___TDES_C_
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore//vendor/OpenSSL__64_bit___TDES_C_/1.1.1
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore//vendor/OpenSSL__64_bit___TDES_C_/1.1.1/12345
ACVPProxy (22:46:19) (acvp-proxy) Verbose - File backend: data written for testID 12345 to file login_response-20200728_22-46-19.debug
ACVPProxy (22:46:19) (acvp-proxy) Debug: ACVP vector: {
  "accessToken":"eyJhbGciOiJIUzI1NiIsInR-truncated_byMe",
  "largeEndpointRequired":false,
  "sizeConstraint":-1
}
ACVPProxy (22:46:19) (acvp-proxy) Debug: ACVP version: {
  "acvVersion":"1.0"
}
ACVPProxy (22:46:19) (acvp-proxy) Debug: Found boolean largeEndpointRequired with value 0
ACVPProxy (22:46:19) (acvp-proxy) Debug: Maximum message size: 4294967295
ACVPProxy (22:46:19) (acvp-proxy) Debug: Found string data accessToken with value eyJhbGciOiJIUzI1NiIsInR-truncated_byMe
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore/
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore//vendor
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore//vendor/OpenSSL__64_bit___TDES_C_
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore//vendor/OpenSSL__64_bit___TDES_C_/1.1.1
ACVPProxy (22:46:19) (acvp-proxy) Debug - File backend: Processing directory ./secure-datastore//vendor/OpenSSL__64_bit___TDES_C_/1.1.1/12345
ACVPProxy (22:46:19) (acvp-proxy) Verbose - File backend: JWT access token stored in ./secure-datastore//vendor/OpenSSL__64_bit___TDES_C_/1.1.1/12345/jwt_authtoken.txt
ACVPProxy (22:46:19) (acvp-proxy) Debug - HTTP operation: HTTP Authentication header: Authorization: Bearer eyJhbGciOiJIUzI1NiIs-truncated_byMe
ACVPProxy (22:46:19) (acvp-proxy) Debug - HTTP operation: Performing an HTTP GET operation
ACVPProxy (22:46:19) (acvp-proxy) Verbose - HTTP operation: TLS peer verification enabled with CA file /home/tom/keys/mozzila_trust_anchors.pem.
ACVPProxy (22:46:19) (acvp-proxy) Debug - HTTP operation: Setting certificate with type PEM
ACVPProxy (22:46:19) (acvp-proxy) Debug - HTTP operation: Setting private key with type PEM
*   Trying 52.204.191.193:443...
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/tom/keys/mozzila_trust_anchors.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Maryland; L=Gaithersburg; O=National Institute of Standards and Technology; OU=STVM ACVP; CN=demo.acvts.nist.gov
*  start date: Jun  1 00:00:00 2020 GMT
*  expire date: Jun 20 12:00:00 2021 GMT
*  subjectAltName: host "demo.acvts.nist.gov" matched cert's "demo.acvts.nist.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /acvp/v1/testSessions/12345 HTTP/1.1
Host: demo.acvts.nist.gov
User-Agent: ACVPProxy/1.5.1
Accept: */*
Authorization: Bearer eyJhbGciOiJIUz-truncated_byMe

* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Transfer-Encoding: chunked
< Server: Microsoft-IIS/8.5
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Date: Tue, 28 Jul 2020 20:46:16 GMT
< 
* Connection #0 to host demo.acvts.nist.gov left intact
ACVPProxy (22:46:20) (acvp-proxy) Warning - HTTP operation: Unable to HTTP GET data for URL https://demo.acvts.nist.gov:443/acvp/v1/testSessions/12345: 403
ACVPProxy (22:46:20) (acvp-proxy) Debug - HTTP operation: HTTP return code: 403
ACVPProxy (22:46:20) (acvp-proxy) Error: Failure in processing testID 12345 with vsID 0 (-403) for module OpenSSL (64 bit) (TDES_C) (TDES_C)
https://demo.acvts.nist.gov:443/acvp/v1/testSessions/12345
ACVPProxy (22:46:20) (acvp-proxy) Warning: ACVP server did not provide meta data for testSession ID 12345
ACVPProxy (22:46:20) (signal0) Verbose - Signal handler: thread terminated
ACVPProxy (22:46:20) (totp0) Verbose - TOTP MQ System: terminate server
ACVPProxy (22:46:20) (acvp-proxy) Verbose - Threading support: Thread 512 killed
ACVPProxy (22:46:20) (acvp-proxy) Verbose - Threading support: Thread 514 killed
Command invocation returned 22

regards,
Thomas

**Comment by smuellerDD** [comment]
Am Mittwoch, 29. Juli 2020, 07:05:23 CEST schrieb tomstom:

Hi tomstom,

> Good morning,
> 
> Ok, here is the part of the log:
> 
> ACVPProxy (22:45:55) (acvp-proxy) Verbose: ACVP URL:
> https://demo.acvts.nist.gov:443/acvp/v1/testSessions ACVPProxy (22:45:55)
> (acvp-proxy) Verbose: testID URL:
> https://demo.acvts.nist.gov:443/acvp/v1/testSessions/12345 ACVPProxy
> (22:45:55) (acvp-proxy) Verbose: (Re)Try testID 12345
> ACVPProxy (22:45:55) (acvp-proxy) Debug: Existing test session JWT access
> token has sufficient lifetime ACVPProxy (22:45:55) (acvp-proxy) Debug -
> HTTP operation: HTTP Authentication header: Authorization: Bearer
> eyJhbGciOiJIUzI-trunceted_byMe ACVPProxy
> (22:45:55) (acvp-proxy) Debug -
> HTTP operation: Performing an HTTP GET operation ACVPProxy
> (22:45:55)
> (acvp-proxy) Verbose - HTTP operation: TLS peer verification enabled with
> CA file /home/tom/keys/mozzila_trust_anchors.pem.
> ACVPProxy (22:45:55)
> (acvp-proxy) Debug - HTTP operation: Setting certificate with type PEM
> ACVPProxy (22:45:55) (acvp-proxy) Debug - HTTP operation: Setting private
> key with type PEM *   Trying 52.204.191.193:443...
> * Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /home/tom/keys/mozzila_trust_anchors.pem
>   CApath: none
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
> * ALPN, server did not agree to a protocol
> * Server certificate:
> *  subject: C=US; ST=Maryland; L=Gaithersburg; O=National Institute of
> Standards and Technology; OU=STVM ACVP; CN=demo.acvts.nist.gov *  start
> date: Jun  1 00:00:00 2020 GMT
> *  expire date: Jun 20 12:00:00 2021 GMT
> *  subjectAltName: host "demo.acvts.nist.gov" matched cert's
> "demo.acvts.nist.gov" *  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2
> Secure Server CA *  SSL certificate verify ok.
> 
> > GET /acvp/v1/testSessions/12345 HTTP/1.1
> 
> Host: demo.acvts.nist.gov
> User-Agent: ACVPProxy/1.5.1
> Accept: */*
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsIn-truncated_byMe
> 
> * old SSL session ID is stale, removing
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 403 Forbidden
> < Transfer-Encoding: chunked
> < Server: Microsoft-IIS/8.5
> < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

A 403 at this point without any returned information by the server and that is 
still shown after a renewing of the JWT has the following possibilities:

1. Your client certificate expired - please check your certificate

2. Your client certificate did not meet the new checks that are enforced since 
last week - please check with Jason Arnold from NIST on either having your 
certificate renewed or getting it re-instantiated

Ciao
Stephan

**Comment by tomstom** [comment]
Hi Stephan,

it seems to be an issue by the server, a new session with the same "config" were finished without any problem. 

So, thank you for your support and for the work you did to the proxy and the parser.

Bye,
Thomas
