### ISSUE TITLE
HMAC and SHA Vectors Only

### ISSUE THREAD

**Issue by mikebusa4** [smuellerDD/acvpproxy#18]
More of a question than an issue: When requesting all available test vectors with the command `acvp-proxy --request` the test vectors for the SHA and HMAC modules are returned. However, as specified in the documentation, by not providing a module with -m <cryptomodule>, this should return all available modules, including AES, ECDSA, etc. Is there a reason only HMAC and SHA test vectors are being returned?

**Comment by smuellerDD** [comment]
Am Montag, dem 11.01.2021 um 13:40 -0800 schrieb mikebusa4:
> More of a question than an issue: When requesting all available test vectors
> with the command `acvp-proxy --request` the test vectors for the SHA and
> HMAC modules are returned. However, as specified in the documentation, by
> not providing a module with -m <cryptomodule>, this should return all
> available modules, including AES, ECDSA, etc. Is there a reason only HMAC
> and SHA test vectors are being returned? 

The proxy operates on instantiated modules. Instantiated modules are a link
between the static cipher definitions (found in C, e.g.
lib/module_implementations/) and the meta data describing the module (e.g. in
module_definitions).

You can list them via acvp-proxy -l.

When it is stated that a certain search scope is applied (or not applied when
no specific scope options are provided), all instantiated module definitions
listed with -l are processed.

You can apply that search scope and check its result by using -l. Once you
found your right search scope of module instances to process, you can replace
the -l with the command you want, e.g. --request.

If you only have instantiated modules that define a SHA and HMAC, you only get
SHA and HMAC.

**Comment by mikebusa4** [comment]
Understood, thank you.
