### ISSUE TITLE
Cannot receive RSA test vectors

### ISSUE THREAD

**Issue by mikebusa4** [smuellerDD/acvpproxy#19]
I think I understand how to request different ciphers/modules etc, but for some reason, I am getting an error when I try to request the RSA test vectors. 

In my implementations.json file, I have:
{
	"implementations": [
		"SHA_ASM",
	]
}

and the definition_impl_openssl.c is unchanged, so I have both:
[...]{
       /* OpenSSL SHA assembler implementation *******************************/
                SET_IMPLEMENTATION(openssl_sha),
                .algo_name = "OpenSSL",
                .processor = "X86",
                .impl_name = "SHA_ASM",
                .impl_description = "Assembler SHA implementation"
      }[...]

and 

static const struct def_algo openssl_sha [] = {
        [...]
        OPENSSL_RSA_KEYGEN,
        OPENSSL_RSA_SIGGEN,
        OPENSSL_RSA_SIGVER,
        [...]
};

Every time I try to request this module with the command `./acvp-proxy -m "OpenSSL (SHA_ASM)" --request` and get the error:
"ACVPProxy (10:23:12) (tid0) Error: Failure to request testID 0 - module OpenSSL (SHA_ASM) (SHA_ASM)"

I have narrowed it down to definitely those three OPENSSL_RSA_xxxxxx modules, and I am wondering if you know why those three are giving me this issue. I am able to request any other cipher/module using the same method and commands.

Thanks,
-Mike

**Comment by smuellerDD** [comment]
Am Montag, dem 25.01.2021 um 07:26 -0800 schrieb mikebusa4:

Invoke the proxy with all your options and -vvv and search the error - shortly
before it there should be the reason.

Ciao
Stephan

**Comment by mikebusa4** [comment]
Here is where it seems the issue is:

ACVPProxy (11:36:49) (acvp-proxy) Warning - HTTP operation: Unable to HTTP POST data for URL https://demo.acvts.nist.gov:443/acvp/v1/testSessions: 400
ACVPProxy (11:36:49) (acvp-proxy) Debug - HTTP operation: HTTP return code: 400
ACVPProxy (11:36:49) (acvp-proxy) Verbose: Process following server response: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map RSA-keyGen-1.0 - index 10 to an internal algorithm id.",
      "Unable to map RSA-sigGen-1.0 - index 11 to an internal algorithm id.",
      "Unable to map RSA-sigVer-1.0 - index 12 to an internal algorithm id."
    ]
  }
]

**Comment by smuellerDD** [comment]
Am Montag, dem 25.01.2021 um 08:39 -0800 schrieb mikebusa4:


Then it seems you use an old proxy code -
https://github.com/smuellerDD/acvpproxy/blob/master/lib/requests/rsa.c#L658 is
the code line that provides the necessary support.

**Comment by mikebusa4** [comment]
Ok so that seemed to fix that issue, I am now getting:
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "RSA-sigGen-FIPS186-4: Invalid Hash Algorithms supplied: SHA-1;Invalid Hash Algorithms supplied: SHA-1;Invalid Hash Algorithms supplied: SHA-1;Invalid Hash Algorithms supplied: SHA-1;Invalid Hash Algorithms supplied: SHA-1;Invalid Hash Algorithms supplied: SHA-1;Invalid Hash Algorithms supplied: SHA-1;Invalid Hash Algorithms supplied: SHA-1;Invalid Hash Algorithms supplied: SHA-1"
    ]
  }
]

And I can't seem to find where I am including the "invalid" SHA-1

**Comment by smuellerDD** [comment]
Recently it was changed to remove RSA with SHA1. So remove it from your RSA siggen.

Ciao
Stephan

—
Cui bono?
