### ISSUE TITLE
No indication of these ciphers existing on the demo server, any way to request them?

### ISSUE THREAD

**Issue by mikebusa** [smuellerDD/acvpproxy#21]
According to the [NIST ACVP site](https://pages.nist.gov/ACVP/) the two algorithms below are supported, but there seems to be no reference to or indication of existence in any of the code or documentation that these algorithms are "requestable":

RSA mode: legacySigVer - HTML
ECDSA mode: sigGenComponent - HTML

Is there any way to use this proxy code to request test vectors for these algorithms?

**Comment by smuellerDD** [comment]
Am Montag, dem 08.02.2021 um 11:43 -0800 schrieb mikebusa:
> According to the [NIST ACVP site](https://pages.nist.gov/ACVP/) the two
> algorithms below are supported, but there seems to be no reference to or
> indication of existence in any of the code or documentation that these
> algorithms are "requestable":
> 
> RSA mode: legacySigVer - HTML

struct def_algo_rsa->rsa_mode which defines DEF_ALG_RSA_MODE_LEGACY_SIGVER

> ECDSA mode: sigGenComponent - HTML

See struct def_algo_ecdsa->component_test

Example

```
#define CPACF_ECDSA_SIGGEN						\
	{								\
	.type = DEF_ALG_TYPE_ECDSA,					\
	.algo = {							\
		.ecdsa = {						\
			.ecdsa_mode = DEF_ALG_ECDSA_MODE_SIGGEN,	\
			.curve = ACVP_NISTP256 | 			\
				 ACVP_NISTP384 |
ACVP_NISTP521,		\
			.hashalg = ACVP_SHA224 | ACVP_SHA256 |		\
				   ACVP_SHA384 | ACVP_SHA512,		\
			.component_test =
true,				\
			}						\
		}							\
	}

#define CPACF_ECDSA_SIGVER						\
	{								\
	.type = DEF_ALG_TYPE_ECDSA,					\
	.algo = {							\
		.ecdsa = {						\
			.ecdsa_mode = DEF_ALG_ECDSA_MODE_SIGVER,	\
			.curve = ACVP_NISTP256 |			\
				 ACVP_NISTP384 |
ACVP_NISTP521,		\
			.hashalg = ACVP_SHA1 | ACVP_SHA224 | ACVP_SHA256 | \
				   ACVP_SHA384 | ACVP_SHA512,		\
			.component_test =
true,				\
			}						\
		}							\
	}
```
> 
> Is there any way to use this proxy code to request test vectors for these
> algorithms?
>

**Comment by mikebusa** [comment]
I still cannot request vectors for RSA legacy sigVer, with this response:

{
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map RSA-legacySigVer-FIPS186-2 - index 0 to an internal algorithm id."
    ]
  }

**Comment by smuellerDD** [comment]
Am Freitag, 19. Februar 2021, 20:46:29 CET schrieb mikebusa:


https://github.com/usnistgov/ACVP-Server/issues/80

Ciao
Stephan

**Comment by smuellerDD** [comment]
The issue is fixed in the code

**Comment by mikebusa** [comment]
Thanks.
