### ISSUE TITLE
EDDSA sigGen preHash

### ISSUE THREAD

**Issue by mikebusa** [smuellerDD/acvpproxy#22]
When requesting EDDSA_sigGen, I don't want vectors with preHashing. According to NIST:
   prehash | Whether or not the message is pre-hashed entering the signature function
   context | The context used to generate the signature
   NOTE: The 'context' property will only be present if the 'prehash' group property is set to true.

I have my module defined as follows:
#define OPENSSL_EDDSA_SIGGEN						\
	{								\
	.type = DEF_ALG_TYPE_EDDSA,					\
	.algo = {							\
		.eddsa = {						\
			.eddsa_mode = DEF_ALG_EDDSA_MODE_SIGGEN,	\
			DEF_PREREQS(openssl_rsa_prereqs),		\
			.curve = ACVP_ED448 | ACVP_ED25519,		\
			.eddsa_prehash = DEF_ALG_EDDSA_PREHASH_UNSUPPORTED, \
			}						\
		}							\
	}

When I added the .eddsa_prehash = DEF_ALG_EDDSA_PREHASH_UNSUPPORTED line, it removed most of the preHashed vectors, but left in some of them. I think this is an issue with the server, and not the proxy code, so you might not be able to answer, but I thought I'd give it a shot since you have been very helpful in the past.

**Comment by smuellerDD** [comment]
Am Freitag, 12. Februar 2021, 19:43:04 CET schrieb mikebusa:

Hi mikebusa,

> When requesting EDDSA_sigGen, I don't want vectors with preHashing.
> According to NIST: prehash | Whether or not the message is pre-hashed
> entering the signature function context | The context used to generate the
> signature
>    NOTE: The 'context' property will only be present if the 'prehash' group
> property is set to true.
> 
> I have my module defined as follows:
> #define OPENSSL_EDDSA_SIGGEN						\
> 	{								\
> 	.type = DEF_ALG_TYPE_EDDSA,					\
> 	.algo = {							\
> 		.eddsa = {						\
> 			.eddsa_mode = DEF_ALG_EDDSA_MODE_SIGGEN,	\
> 			DEF_PREREQS(openssl_rsa_prereqs),		\
> 			.curve = ACVP_ED448 | ACVP_ED25519,		\
> 			.eddsa_prehash = DEF_ALG_EDDSA_PREHASH_UNSUPPORTED, \
> 			}						\
> 		}							\
> 	}
> 
> When I added the .eddsa_prehash = DEF_ALG_EDDSA_PREHASH_UNSUPPORTED line, it
> removed most of the preHashed vectors, but left in some of them. I think
> this is an issue with the server, and not the proxy code, so you might not
> be able to answer, but I thought I'd give it a shot since you have been
> very helpful in the past.

First, your definition seems to be correct. I used a very similar definition 
to obtain testvectors for libsodium (I only had eddsa_pure = 
DEF_ALG_EDDSA_PURE_SUPPORTED in addition). And testing with libsodium was 
successful.

In the past, the testing was successful with that.

After getting new vectors today, however, I also get only test vectors with 
preHash=false.

Here is my definition

```
#define LIBSODIUM_EDDSA_SIGGEN                                          \
        {                                                               \
        .type = DEF_ALG_TYPE_EDDSA,                                     \
        .algo = {                                                       \
                .eddsa = {                                              \
                        .eddsa_mode = DEF_ALG_EDDSA_MODE_SIGGEN,        \
                        DEF_PREREQS(libsodium_eddsa_prereqs),           \
                        .curve = ACVP_ED25519,                          \
                        .eddsa_pure = DEF_ALG_EDDSA_PURE_SUPPORTED,     \
                        .eddsa_prehash = DEF_ALG_EDDSA_PREHASH_UNSUPPORTED,\
                        }                                               \
                }                                                       \
        }
```

Ciao
Stephan

**Comment by mikebusa** [comment]
I am also only getting vectors with preHash = false, but I am getting 10 test cases that have:
...
preHash = false
...
context: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

Despite the fact that preHash = false, there is still a context parameter, and my verification is failing these 10 tests only. According to NIST, when preHash = false, there should be no context parameter, so I'm just confused why I'm getting these.

**Comment by smuellerDD** [comment]
Am Montag, dem 15.02.2021 um 10:08 -0800 schrieb mikebusa:


Interesting, I do not see such context field in my test vectors.

But after playing around it seems that with the addition of ED448, the context
field appears.

This seems to be a bug at the ACVP server - I guess you may want to file a bug
at https://github.com/usnistgov/ACVP-Server

Ciao
Stephan
