### ISSUE TITLE
acvpproxy build error

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#26]
lib/acvp/acvp.o: In function acvp_load_extension': acvp.c:(.text+0x1b5c): undefined reference to dlopen'
acvp.c:(.text+0x1b68): undefined reference to dlerror' acvp.c:(.text+0x1b74): undefined reference to dlsym'
acvp.c:(.text+0x1be0): undefined reference to dlerror' acvp.c:(.text+0x1c00): undefined reference to dlerror'
lib/common/datastore_file.o: In function acvp_datastore_check_version': datastore_file.c:(.text+0x3a8): undefined reference to pthread_rwlock_wrlock'
datastore_file.c:(.text+0x3e4): undefined reference to pthread_rwlock_unlock' datastore_file.c:(.text+0x430): undefined reference to pthread_rwlock_unlock'
datastore_file.c:(.text+0x4ec): undefined reference to pthread_rwlock_unlock' lib/common/network_backend_curl.o: In function acvp_curl_common_init':
network_backend_curl.c:(.text+0x47c): undefined reference to curl_easy_init' network_backend_curl.c:(.text+0x490): undefined reference to curl_easy_setopt'
network_backend_curl.c:(.text+0x4a8): undefined reference to curl_easy_setopt' network_backend_curl.c:(.text+0x4c0): undefined reference to curl_easy_setopt'
network_backend_curl.c:(.text+0x4d8): undefined reference to curl_easy_setopt' network_backend_curl.c:(.text+0x4f0): undefined reference to curl_easy_setopt'
lib/common/network_backend_curl.o:network_backend_curl.c:(.text+0x508): more undefined references to curl_easy_setopt' follow lib/common/network_backend_curl.o: In function acvp_curl_common_init':
network_backend_curl.c:(.text+0x758): undefined reference to curl_easy_cleanup' network_backend_curl.c:(.text+0x7b4): undefined reference to curl_slist_append'
network_backend_curl.c:(.text+0x7d4): undefined reference to curl_easy_setopt' lib/common/network_backend_curl.o: In function acvp_curl_http_common':
network_backend_curl.c:(.text+0x8c4): undefined reference to curl_slist_append' network_backend_curl.c:(.text+0x924): undefined reference to curl_easy_strerror'
network_backend_curl.c:(.text+0x968): undefined reference to curl_easy_perform' network_backend_curl.c:(.text+0x9a4): undefined reference to curl_easy_getinfo'
network_backend_curl.c:(.text+0xa30): undefined reference to curl_easy_cleanup' network_backend_curl.c:(.text+0xa40): undefined reference to curl_slist_free_all'
network_backend_curl.c:(.text+0xaec): undefined reference to curl_easy_setopt' network_backend_curl.c:(.text+0xb4c): undefined reference to curl_easy_setopt'
network_backend_curl.c:(.text+0xb64): undefined reference to curl_easy_setopt' network_backend_curl.c:(.text+0xb80): undefined reference to curl_easy_setopt'
network_backend_curl.c:(.text+0xb98): undefined reference to curl_easy_setopt' lib/common/network_backend_curl.o:network_backend_curl.c:(.text+0xbcc): more undefined references to curl_easy_setopt' follow
lib/common/network_backend_curl.o: In function acvp_curl_http_common': network_backend_curl.c:(.text+0xc24): undefined reference to curl_easy_getinfo'
lib/common/network_backend_curl.o: In function acvp_curl_http_post_multi': network_backend_curl.c:(.text+0xef4): undefined reference to curl_easy_init'
network_backend_curl.c:(.text+0xf04): undefined reference to curl_multi_init' network_backend_curl.c:(.text+0xf14): undefined reference to curl_mime_init'
network_backend_curl.c:(.text+0xf3c): undefined reference to curl_easy_setopt' network_backend_curl.c:(.text+0xf58): undefined reference to curl_multi_add_handle'
network_backend_curl.c:(.text+0xf64): undefined reference to curl_multi_perform' network_backend_curl.c:(.text+0x100c): undefined reference to curl_multi_timeout'
network_backend_curl.c:(.text+0x1054): undefined reference to curl_multi_fdset' network_backend_curl.c:(.text+0x10a4): undefined reference to curl_mime_name'
network_backend_curl.c:(.text+0x10bc): undefined reference to curl_mime_data' network_backend_curl.c:(.text+0x10d8): undefined reference to curl_mime_addpart'
network_backend_curl.c:(.text+0x1100): undefined reference to curl_easy_cleanup' network_backend_curl.c:(.text+0x110c): undefined reference to curl_mime_free'
network_backend_curl.c:(.text+0x111c): undefined reference to curl_slist_free_all' network_backend_curl.c:(.text+0x11a4): undefined reference to curl_multi_cleanup'
network_backend_curl.c:(.text+0x11b8): undefined reference to curl_multi_perform' lib/common/network_backend_curl.o: In function acvp_curl_library_exit':
network_backend_curl.c:(.text+0x1278): undefined reference to curl_global_cleanup' lib/common/network_backend_curl.o: In function acvp_curl_init':
network_backend_curl.c:(.text.startup+0x3c): undefined reference to curl_global_init' lib/common/signal_handler.o: In function sig_handler_thread':
signal_handler.c:(.text+0x330): undefined reference to pthread_sigmask' lib/common/signal_handler.o: In function sig_install_handler':
signal_handler.c:(.text+0x8c4): undefined reference to pthread_sigmask' lib/common/signal_handler.o: In function sig_uninstall_handler':
signal_handler.c:(.text+0x9e0): undefined reference to pthread_kill' lib/acvp/acvp_list_requests.o: In function acvp_list_add_sort':
acvp_list_requests.c:(.text+0x178): undefined reference to pthread_rwlock_wrlock' acvp_list_requests.c:(.text+0x214): undefined reference to pthread_rwlock_unlock'
lib/acvp/acvp_list_requests.o: In function acvp_list_print_sort': acvp_list_requests.c:(.text+0x5a8): undefined reference to pthread_rwlock_wrlock'
acvp_list_requests.c:(.text+0x630): undefined reference to pthread_rwlock_unlock' lib/acvp/acvp_list_requests.o: In function acvp_list_request_id_sparse':
acvp_list_requests.c:(.text+0xb70): undefined reference to pthread_rwlock_wrlock' acvp_list_requests.c:(.text+0xbdc): undefined reference to pthread_rwlock_unlock'
acvp_list_requests.c:(.text+0xcc0): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_register_def':
definition.c:(.text+0x1e8): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x270): undefined reference to pthread_rwlock_unlock'
lib/acvp/definition.o: In function acvp_def_read_json': definition.c:(.text+0x1428): undefined reference to pthread_rwlock_rdlock'
definition.c:(.text+0x1464): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_def_write_json':
definition.c:(.text+0x17f4): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x1828): undefined reference to pthread_rwlock_unlock'
lib/acvp/definition.o: In function acvp_def_alloc_lock': definition.c:(.text+0x1d9c): undefined reference to pthread_rwlock_init'
lib/acvp/definition.o: In function acvp_find_def': definition.c:(.text+0x1e70): undefined reference to pthread_rwlock_rdlock'
definition.c:(.text+0x1ee4): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_list_unregistered_definitions':
definition.c:(.text+0x2480): undefined reference to pthread_rwlock_rdlock' definition.c:(.text+0x24c0): undefined reference to pthread_rwlock_unlock'
lib/acvp/definition.o: In function acvp_def_release_all': definition.c:(.text+0x36e0): undefined reference to pthread_rwlock_wrlock'
definition.c:(.text+0x3744): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_def_get_vendor_id':
definition.c:(.text+0x37a4): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x383c): undefined reference to pthread_rwlock_unlock'
lib/acvp/definition.o: In function acvp_def_put_vendor_id': definition.c:(.text+0x38e8): undefined reference to pthread_rwlock_unlock'
lib/acvp/definition.o: In function acvp_def_get_person_id': definition.c:(.text+0x39ac): undefined reference to pthread_rwlock_wrlock'
definition.c:(.text+0x3a70): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_def_put_person_id':
definition.c:(.text+0x3b00): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_def_get_oe_id':
definition.c:(.text+0x3bb4): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x3d1c): undefined reference to pthread_rwlock_unlock'
definition.c:(.text+0x3d3c): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_def_put_oe_id':
definition.c:(.text+0x3fec): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_def_update_oe_config':
definition.c:(.text+0x4218): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x42b4): undefined reference to pthread_rwlock_unlock'
definition.c:(.text+0x43bc): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x43d8): undefined reference to pthread_rwlock_unlock'
lib/acvp/definition.o: In function acvp_def_get_module_id': definition.c:(.text+0x4538): undefined reference to pthread_rwlock_wrlock'
definition.c:(.text+0x45a4): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_def_put_module_id':
definition.c:(.text+0x4664): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x4810): undefined reference to pthread_rwlock_unlock'
lib/acvp/definition.o: In function acvp_def_update_module_config': definition.c:(.text+0x4954): undefined reference to pthread_rwlock_wrlock'
definition.c:(.text+0x4970): undefined reference to pthread_rwlock_unlock' lib/acvp/definition.o: In function acvp_def_config':
definition.c:(.text+0x5118): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x52a8): undefined reference to pthread_rwlock_unlock'
definition.c:(.text+0x53ac): undefined reference to pthread_rwlock_wrlock' definition.c:(.text+0x57d8): undefined reference to pthread_rwlock_unlock'
lib/acvp/definition.o: In function acvp_register_algo_map': definition.c:(.text+0x5c44): undefined reference to pthread_rwlock_wrlock'
definition.c:(.text+0x5cc0): undefined reference to pthread_rwlock_unlock' lib/common/authtoken.o: In function _acvp_init_auth':
authtoken.c:(.text+0x5ac): undefined reference to pthread_rwlock_init' lib/common/authtoken.o: In function acvp_release_auth_ctx':
authtoken.c:(.text+0x7a4): undefined reference to pthread_rwlock_destroy' lib/common/authtoken.o: In function acvp_release_auth':
authtoken.c:(.text+0x848): undefined reference to pthread_rwlock_destroy' lib/common/authtoken.o: In function acvp_get_max_msg_size':
authtoken.c:(.text+0xb6c): undefined reference to pthread_rwlock_wrlock' authtoken.c:(.text+0xb7c): undefined reference to pthread_rwlock_unlock'
lib/common/authtoken.o: In function acvp_login': authtoken.c:(.text+0xe5c): undefined reference to pthread_rwlock_wrlock'
authtoken.c:(.text+0xe64): undefined reference to pthread_rwlock_wrlock' authtoken.c:(.text+0xe80): undefined reference to pthread_rwlock_unlock'
authtoken.c:(.text+0xe88): undefined reference to pthread_rwlock_unlock' authtoken.c:(.text+0x10e4): undefined reference to pthread_rwlock_unlock'
authtoken.c:(.text+0x10ec): undefined reference to pthread_rwlock_unlock' lib/common/authtoken.o: In function acvp_login_refresh':
authtoken.c:(.text+0x1364): undefined reference to pthread_rwlock_wrlock' authtoken.c:(.text+0x1400): undefined reference to pthread_rwlock_unlock'
lib/common/network_helper.o: In function _acvp_net_op': network_helper.c:(.text+0x9c): undefined reference to pthread_rwlock_rdlock'
network_helper.c:(.text+0xe4): undefined reference to pthread_rwlock_unlock' network_helper.c:(.text+0x238): undefined reference to pthread_rwlock_unlock'
network_helper.c:(.text+0x294): undefined reference to pthread_rwlock_unlock' lib/common/openssl_thread_support.o: In function thread_cleanup':
openssl_thread_support.c:(.text+0x5c): undefined reference to CRYPTO_set_id_callback' openssl_thread_support.c:(.text+0x68): undefined reference to CRYPTO_set_locking_callback'
openssl_thread_support.c:(.text+0x80): undefined reference to CRYPTO_num_locks' lib/common/openssl_thread_support.o: In function acvp_openssl_thread_setup':
openssl_thread_support.c:(.text+0x24c): undefined reference to CRYPTO_num_locks' openssl_thread_support.c:(.text+0x294): undefined reference to CRYPTO_num_locks'
openssl_thread_support.c:(.text+0x2a4): undefined reference to CRYPTO_set_id_callback' openssl_thread_support.c:(.text+0x2ac): undefined reference to CRYPTO_set_locking_callback'
lib/common/threading_support.o: In function thread_worker': threading_support.c:(.text+0x6c): undefined reference to pthread_sigmask'
lib/common/threading_support.o: In function thread_wait': threading_support.c:(.text+0x460): undefined reference to pthread_mutex_trylock'
lib/common/threading_support.o: In function thread_set_name': threading_support.c:(.text+0x5b0): undefined reference to pthread_setname_np'
lib/common/threading_support.o: In function thread_get_name': threading_support.c:(.text+0x660): undefined reference to pthread_getname_np'
lib/common/threading_support.o: In function thread_start': threading_support.c:(.text+0x82c): undefined reference to pthread_mutex_trylock'
threading_support.c:(.text+0x998): undefined reference to pthread_create' lib/common/threading_support.o: In function thread_release':
threading_support.c:(.text+0xbdc): undefined reference to pthread_cancel' threading_support.c:(.text+0xbe8): undefined reference to pthread_join'
threading_support.c:(.text+0xd58): undefined reference to pthread_join' lib/common/totp_mq_server.o: In function totp_mq_start':
totp_mq_server.c:(.text+0x4b4): undefined reference to pthread_rwlock_wrlock' totp_mq_server.c:(.text+0x644): undefined reference to pthread_rwlock_unlock'
collect2: error: ld returned 1 exit status

kindly help

**Comment by smuellerDD** [comment]
Am Sonntag, 25. April 2021, 08:16:41 CEST schrieb shilpa-1992:

Hi shilpa,


I guess you need to fix your linking - you do not link to libcurl, libpthread 
and libcrypto.



Ciao
Stephan

**Comment by shilpa-1992** [comment]
Tried adding LIBS=" " as well as in LDFLAGS .... But did not resolve my problem. Could you please suggest a way to fix this linking issue. 

Thanks in advance.
