### ISSUE TITLE
Build failure in acvpproxy

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#27]
/gnu-cross/linux_64/13/generic/bin/../lib/gcc/powerpc-generic-linux-gnu/4.8.2/../../../../powerpc-generic-linux-gnu/bin/ld: apps/base64.o: Relocations in generic ELF (EM: 62)
apps/base64.o: could not read symbols: File in wrong format
collect2: error: ld returned 1 exit status

Tried compiling the code and got struck in this error. 
Any clue to this error

**Comment by smuellerDD** [comment]
Am Dienstag, dem 27.04.2021 um 05:54 -0700 schrieb shilpa-1992:
> /gnu-cross/linux_64/13/generic/bin/../lib/gcc/powerpc-generic-linux-
> gnu/4.8.2/../../../../powerpc-generic-linux-gnu/bin/ld: apps/base64.o:
> Relocations in generic ELF (EM: 62)
> apps/base64.o: could not read symbols: File in wrong format
> collect2: error: ld returned 1 exit status

make clean && make

The .o file seem to have been created wrongly by your tool chain.
> 
> Tried compiling the code and got struck in this error. 
> Any clue to this error
> 
>
