### ISSUE TITLE
Acvp server connection issue:

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [smuellerDD/acvpproxy#28]
Hello,

I am getting below error , while connecting to server. Please let me know how i can resolve this

/src/acvpproxy$ ./acvp-proxy --cipher-list -v
ACVPProxy (07:27:02) (acvp-proxy) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (07:27:02) (acvp-proxy) Status: Logging into ACVP server
ACVPProxy (07:27:03) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 35 (SSL connect error)
ACVPProxy (07:27:13) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 35 (SSL connect error)
ACVPProxy (07:27:24) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 35 (SSL connect error)
ACVPProxy (07:27:24) (acvp-proxy) Warning - HTTP operation: Unable to HTTP POST data for URL https://demo.acvts.nist.gov:443/acvp/v1/login: 0
ACVPProxy (07:27:24) (acvp-proxy) Error: No response data found
ACVPProxy (07:27:24) (acvp-proxy) Error: Failure in processing testID 0 with vsID 0 (-22) for module <undefined> (<undefined>)

Thnaks
Nag

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 28.04.2021 um 07:54 -0700 schrieb Nagarjun:
> Hello,
> 
> I am getting below error , while connecting to server. Please let me know
> how i can resolve this
> 
> /src/acvpproxy$ ./acvp-proxy --cipher-list -v
> ACVPProxy (07:27:02) (acvp-proxy) Status - TOTP MQ System: Requesting OTP
> value, waiting ...
> ACVPProxy (07:27:02) (acvp-proxy) Status: Logging into ACVP server
> ACVPProxy (07:27:03) (acvp-proxy) Warning - HTTP operation: Curl HTTP
> operation failed with code 35 (SSL connect error)
> ACVPProxy (07:27:13) (acvp-proxy) Warning - HTTP operation: Curl HTTP
> operation failed with code 35 (SSL connect error)
> ACVPProxy (07:27:24) (acvp-proxy) Warning - HTTP operation: Curl HTTP
> operation failed with code 35 (SSL connect error)
> ACVPProxy (07:27:24) (acvp-proxy) Warning - HTTP operation: Unable to HTTP
> POST data for URL https://demo.acvts.nist.gov:443/acvp/v1/login: 0
> ACVPProxy (07:27:24) (acvp-proxy) Error: No response data found
> ACVPProxy (07:27:24) (acvp-proxy) Error: Failure in processing testID 0 with
> vsID 0 (-22) for module <undefined> (<undefined>)

I see that issue right now as well. The server seems to be unresponsive.

Use -vvv to see exactly what the proxy is doing.

Ciao
Stephan
> 
> Thnaks
> Nag
> 
> 
> 
> 
>

**Comment by Nagarjuna-jantali** [comment]
> Am Mittwoch, dem 28.04.2021 um 07:54 -0700 schrieb Nagarjun:
> Hello, I am getting below error , while connecting to server. Please let me know how i can resolve this /src/acvpproxy$ ./acvp-proxy --cipher-list -v ACVPProxy (07:27:02) (acvp-proxy) Status - TOTP MQ System: Requesting OTP value, waiting ... ACVPProxy (07:27:02) (acvp-proxy) Status: Logging into ACVP server ACVPProxy (07:27:03) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 35 (SSL connect error) ACVPProxy (07:27:13) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 35 (SSL connect error) ACVPProxy (07:27:24) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 35 (SSL connect error) ACVPProxy (07:27:24) (acvp-proxy) Warning - HTTP operation: Unable to HTTP POST data for URL https://demo.acvts.nist.gov:443/acvp/v1/login: 0 ACVPProxy (07:27:24) (acvp-proxy) Error: No response data found ACVPProxy (07:27:24) (acvp-proxy) Error: Failure in processing testID 0 with vsID 0 (-22) for module <undefined> (<undefined>)
> I see that issue right now as well. The server seems to be unresponsive. Use -vvv to see exactly what the proxy is doing. Ciao Stephan
> […](#)
> Thnaks Nag

Hello,

Used --vvv,


CVPProxy (08:20:38) (acvp-proxy) Debug - HTTP operation: Setting certificate with type PEM
ACVPProxy (08:20:38) (acvp-proxy) Debug - HTTP operation: Setting private key with type PEM
ACVPProxy (08:20:38) (acvp-proxy) Debug - HTTP operation: Performing an HTTP POST operation
*   Trying 52.204.191.193...
* TCP_NODELAY set
*   Trying 2600:1f18:268d:1d01:acfb:16e5:57b4:96ac...
* TCP_NODELAY set
* Immediate connect fail for 2600:1f18:268d:1d01:acfb:16e5:57b4:96ac: Network is unreachable
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
* found 129 certificates in /etc/ssl/certs/ca-certificates.crt
* found 391 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* error reading X.509 potentially-encrypted key file: ASN1 parser: Error in TAG.
* Closing connection 0
ACVPProxy (08:20:40) (acvp-proxy) Warning - HTTP operation: Curl HTTP operation failed with code 35 (SSL connect error)
* Hostname demo.acvts.nist.gov was found in DNS cache
*   Trying 52.204.191.193...
* TCP_NODELAY set
*   Trying 2600:1f18:268d:1d01:acfb:16e5:57b4:96ac...
* TCP_NODELAY set
* Immediate connect fail for 2600:1f18:268d:1d01:acfb:16e5:57b4:96ac: Network is unreachable
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#1)
* found 129 certificates in /etc/ssl/certs/ca-certificates.crt
* found 391 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* error reading X.509 potentially-encrypted key file: ASN1 parser: Error in TAG.
* Closing connection 1

Is this related to certificates , i have stored certificates ,seed file and acvpproxy_conf.json  in main  folder where acvp_proxy binary is present.

Thanks,
NAG

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 28.04.2021 um 08:53 -0700 schrieb Nagarjun:
> > 
> * error reading X.509 potentially-encrypted key file: ASN1 parser: Error in
> TAG.

That looks like your issue: you have an encrypted private key and it seems you
did not provide the passcode of the private key to the config file.

Ciao
Stephan

**Comment by Nagarjuna-jantali** [comment]
> Am Mittwoch, dem 28.04.2021 um 08:53 -0700 schrieb Nagarjun:
> > * error reading X.509 potentially-encrypted key file: ASN1 parser: Error in TAG.
> That looks like your issue: you have an encrypted private key and it seems you did not provide the passcode of the private key to the config file. Ciao Stephan

**Comment by Nagarjuna-jantali** [comment]
I

**Comment by Nagarjuna-jantali** [comment]
> Am Mittwoch, dem 28.04.2021 um 08:53 -0700 schrieb Nagarjun:
> > * error reading X.509 potentially-encrypted key file: ASN1 parser: Error in TAG.
> That looks like your issue: you have an encrypted private key and it seems you did not provide the passcode of the private key to the config file. Ciao Stephan

Hello,

I have not provided any password to private key.

Thanks,
Nag

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 28.04.2021 um 09:17 -0700 schrieb Nagarjun:
> > Am Mittwoch, dem 28.04.2021 um 08:53 -0700 schrieb Nagarjun:
> > > * error reading X.509 potentially-encrypted key file: ASN1 parser: Error
> > > in TAG.
> > That looks like your issue: you have an encrypted private key and it seems
> > you did not provide the passcode of the private key to the config file.
> > Ciao Stephan
> 
> Hello,
> 
> I have not provided any password to private key.

The log mentions that the file cannot be opened. Usually it is a passcode
issue. But maybe you have a file type that is not recognized - see the
README.md for supported data types for keys.
> 
> Thanks,
> Nag
>

**Comment by Nagarjuna-jantali** [comment]
Able to login to server.

thanks
Nag

**Comment by Nagarjuna-jantali** [comment]
Login issue resolved
