### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#29]
Hello,

Could you please share sample test vectors and test response for safeprimes, DH and ECDH.

Regards,

**Comment by smuellerDD** [comment]
Am Freitag, dem 30.04.2021 um 02:54 -0700 schrieb shilpa-1992:
> Hello,
> 
> Could you please share sample test vectors and test response for safeprimes,
> DH and ECDH.

I do not think that brings anything because those are not known-answer tests.
Keys are being generated.

Ciao
Stephan
> 
> Regards,
>
