### ISSUE TITLE
Tool Execution

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#30]
I have integrated the ACVPPROXY AND ACVPPARSER code to my tps and build is through which resulted in acvp-parser and acvp-proxy binary. 

Please correct my understanding if its wrong.

1. I need to take these two binary (separately to switch) to execute the same.
2. Now give openssl command to create a certificate signed request
openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr
After that, we need to send csr file to NIST to request certificate and TOTP seed.
3.When we get cert and seed from NIST, we put these file into the switch and configure the path to these files in acvpproxy_conf.json file.
4. Create a module cipher definition.
5. 
    1.	Download all ACVP test vectors:
       acvp-proxy –request
    2.	Download the ACVP test vectors for the chosen cryptographic module:
        acvp-proxy -m <cryptomodule> --request
6. After finishing download these test vectors, acvpproxy will put these test vector into the test vectors folder. You can use acvpparser to run test vector and generate test response.
              ls -l testvectors/atsec_corp_/
7. Issue this command to run acvpparser
        acvp-parser <directory>/testvector-request.json <directory>/testvector-response.json
8.	Upload test response to acv server:
        acvp-proxy -m <cryptomodule>
        Ex: acvp-proxy -m "OpenSSL (32 bit) (SHA_ASM)"
        
could you please provide clarification to few of my doubts too.

a. What are the Process to be followed to send server.csr file to NIST ?
b. What all modification to be provided in a directory `module_definitions` and do i need to take the whole directory to my networking switch?
c. Which platforms do we need to get certificate? 
   Do we need to create separate module cipher definition for each platforms?

.

**Comment by smuellerDD** [comment]
Am Sonntag, dem 02.05.2021 um 22:35 -0700 schrieb shilpa-1992:
> I have integrated the ACVPPROXY AND ACVPPARSER code to my tps and build is
> through which resulted in acvp-parser and acvp-proxy binary. 
> 
> Please correct my understanding if its wrong.
> 
> 1. I need to take these two binary (separately to switch) to execute the
> same.
> 2. Now give openssl command to create a certificate signed request
> openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr
> After that, we need to send csr file to NIST to request certificate and TOTP
> seed.
> 3.When we get cert and seed from NIST, we put these file into the switch and
> configure the path to these files in acvpproxy_conf.json file.
> 4. Create a module cipher definition.
> 5. 
>     1.  Download all ACVP test vectors:
>        acvp-proxy –request
>     2.  Download the ACVP test vectors for the chosen cryptographic module:
>         acvp-proxy -m <cryptomodule> --request
> 6. After finishing download these test vectors, acvpproxy will put these
> test vector into the test vectors folder. You can use acvpparser to run test
> vector and generate test response.
>               ls -l testvectors/atsec_corp_/
> 7. Issue this command to run acvpparser
>         acvp-parser <directory>/testvector-request.json
> <directory>/testvector-response.json
> 8.      Upload test response to acv server:
>         acvp-proxy -m <cryptomodule>
>         Ex: acvp-proxy -m "OpenSSL (32 bit) (SHA_ASM)"
>         
> could you please provide clarification to few of my doubts too.
> 
> a. What are the Process to be followed to send server.csr file to NIST ?

See NIST's ACVTS page for requesting credentials.

> b. What all modification to be provided in a directory `module_definitions`
> and do i need to take the whole directory to my networking switch?

See README.md for the module_definitions.

I have no idea what you mean about the networking switch.

> c. Which platforms do we need to get certificate? 
>    Do we need to create separate module cipher definition for each
> platforms?

I guess that is what your lab and your PR folks will tell you.

Ciao
Stephan
