### ISSUE TITLE
How to download SP800-56 rev3 vectors

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [smuellerDD/acvpproxy#31]
Its a query:

HI

I am able to login to demo server, Please suggest me  how can i download sp800-56 rev3 vectors from demo server.

Thanks
Nag

**Comment by smuellerDD** [comment]
Am Montag, dem 03.05.2021 um 02:51 -0700 schrieb Nagarjun:
> Its a query:
> 
> HI
> 
> I am able to login to demo server, Please suggest me  how can i download
> sp800-56 rev3 vectors from demo server.
> 

KAS_FFC and KAS_ECC vectors that can be obtained with the OpenSSL definition
are 56 rev3 tests.

Ciao
Stephan
> 
> Thanks
> Nag
>

**Comment by Nagarjuna-jantali** [comment]
> Am Montag, dem 03.05.2021 um 02:51 -0700 schrieb Nagarjun:
> Its a query: HI I am able to login to demo server, Please suggest me  how can i download sp800-56 rev3 vectors from demo server.
> KAS_FFC and KAS_ECC vectors that can be obtained with the OpenSSL definition are 56 rev3 tests. Ciao Stephan
> […](#)
> Thanks Nag

Hi

I am using openssl-1.0.2l with 2.0.16[FOM] , do i need to register the module and download them?  i

Thanks
Nag

**Comment by smuellerDD** [comment]
Am Montag, dem 03.05.2021 um 03:25 -0700 schrieb Nagarjun:
> > Am Montag, dem 03.05.2021 um 02:51 -0700 schrieb Nagarjun:
> > Its a query: HI I am able to login to demo server, Please suggest me  how
> > can i download sp800-56 rev3 vectors from demo server.
> > KAS_FFC and KAS_ECC vectors that can be obtained with the OpenSSL
> > definition are 56 rev3 tests. Ciao Stephan
> > […](#)
> > Thanks Nag
> 
> Hi
> 
> I am using openssl-1.0.2l with 2.0.16[FOM] , do i need to register the
> module and download them?  i

I recommend you read the acvpproxy/README.md and the acvpparser/README.md

Ciao
Stephan
