### ISSUE TITLE
How do i check my acvpparser works fine.

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#33]
let the JSON object sent from the server to the client for safePrimes / keyGen / 1.0 copied to bin where all other binaries are present

[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "safePrimes",
        "mode": "keyGen",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "safePrimeGroup": "ffdhe2048",
                "testType": "AFT",
                "tests": [
                    {
                        "tcId": 1
                    },
                    {
                        "tcId": 2
                    },
                    {
                        "tcId": 3
                    }
                ]
            },
            {
                "tgId": 2,
                "testType": "AFT",
                "safePrimeGroup": "MODP-2048",
                "tests": [
                    {
                        "tcId": 4
                    },
                    {
                        "tcId": 5
                    },
                    {
                        "tcId": 6
                    }
                ]
            }
        ]
    }
]

with "acvp-parser safePrimes / keyGen / 1.0/testvector-request.json safePrimes / keyGen / 1.0/testvector-response.json"
Is "testvector-response.json" expected to generate. Or am making mistake in uploading (only acvp-parser binary and safePrimes / keyGen / 1.0/testvector-request.json uploaded to switch).

**Comment by smuellerDD** [comment]
Am Montag, dem 03.05.2021 um 03:41 -0700 schrieb shilpa-1992:
> 
> with "acvp-parser safePrimes / keyGen / 1.0/testvector-request.json
> safePrimes / keyGen / 1.0/testvector-response.json"
> Is "testvector-response.json" expected to generate. Or am making mistake in
> uploading (only acvp-parser binary and safePrimes / keyGen / 1.0/testvector-
> request.json uploaded to switch).

I do not understand your question. Read the acvpparser/README.md and the
acvpproxy/README.md

Ciao
Stephan
> 
>
