### ISSUE TITLE
KAS-ECC "fullval" testing query 

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [smuellerDD/acvpproxy#34]
Hi

I am trying to download KAS-ECC fullval vector, for that i have modified kas_ecc_function to DEF_ALG_KAS_ECC_FULLVAL. Is this the correct way to get the vector? please suggest.

#define __OPENSSL_KAS_ECC(paramset)                                     \
        {                                                               \
        .type = DEF_ALG_TYPE_KAS_ECC,                                   \
        .algo.kas_ecc = {                                               \
                DEF_PREREQS(openssl_ecdh_prereqs),                      \
                .kas_ecc_function = DEF_ALG_KAS_ECC_FULLVAL,            \
                .kas_ecc_schema = DEF_ALG_KAS_ECC_EPHEMERAL_UNIFIED,    \
                .kas_ecc_role = DEF_ALG_KAS_ECC_INITIATOR |             \
                                DEF_ALG_KAS_ECC_RESPONDER,              \
                .kas_ecc_dh_type = DEF_ALG_KAS_ECC_NO_KDF_NO_KC,        \
                .type_info.nokdfnokc = paramset,                        \
                },                                                      \
        }

Thanks,
Nag

**Comment by smuellerDD** [comment]
Am Dienstag, dem 11.05.2021 um 23:31 -0700 schrieb Nagarjun:
> Hi
> 
> I am trying to download KAS-ECC fullval vector, for that i have modified
> kas_ecc_function to DEF_ALG_KAS_ECC_FULLVAL. Is this the correct way to get
> the vector? please suggest.
> 
> #define __OPENSSL_KAS_ECC(paramset)                                     \
>         {                                                               \
>         .type = DEF_ALG_TYPE_KAS_ECC,                                   \
>         .algo.kas_ecc = {                                               \
>                 DEF_PREREQS(openssl_ecdh_prereqs),                      \
>                 .kas_ecc_function = DEF_ALG_KAS_ECC_FULLVAL,            \
>                 .kas_ecc_schema = DEF_ALG_KAS_ECC_EPHEMERAL_UNIFIED,    \
>                 .kas_ecc_role = DEF_ALG_KAS_ECC_INITIATOR |             \
>                                 DEF_ALG_KAS_ECC_RESPONDER,              \
>                 .kas_ecc_dh_type = DEF_ALG_KAS_ECC_NO_KDF_NO_KC,        \
>                 .type_info.nokdfnokc = paramset,                        \
>                 },                                                      \
>         }

Looks good
> 
> Thanks,
> Nag
> 
>
