### ISSUE TITLE
Cannot open config file

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#35]
Iam getting below error when i try to run ./acvp-proxy -request

vm1@vm1-VirtualBox:~/Desktop/acvpproxy$ ./acvp-proxy -m "OpenSSL (64 bit)" --request
ACVPProxy (18:42:27) (tid0) Status: Register module OpenSSL (64 bit)
ACVPProxy (18:42:27) (tid0) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (18:42:27) (tid0) Status: Register module OpenSSL (64 bit)
ACVPProxy (18:42:27) (tid0) Status: Logging into ACVP server
ACVPProxy (18:42:47) (tid0) Error: No response data found
ACVPProxy (18:42:47) (tid0) Error: Failure to request testID 0 - module OpenSSL (64 bit) ((null))
ACVPProxy (18:42:47) (tid0) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (18:42:57) (tid0) Status: Logging into ACVP server
ACVPProxy (18:43:17) (tid0) Error: No response data found
ACVPProxy (18:43:17) (tid0) Error: Failure to request testID 0 - module OpenSSL (64 bit) ((null))
vm1@vm1-VirtualBox:~/Desktop/acvpproxy$ 

 what might have caused this issue.

**Comment by smuellerDD** [comment]
Am Dienstag, dem 18.05.2021 um 05:47 -0700 schrieb shilpa-1992:
> Iam getting below error when i try to run ./acvp-proxy -request
> 
> (acvp-proxy) Error: Cannot open config file acvpproxy_conf.json
> 
> where is the path acvpproxy_conf.json expected ? what might have caused this
> issue.
> 

I have to admit, I am weary of such questions. The documentation should be
read in its entirety.

**Comment by shilpa-1992** [comment]
vm1@vm1-VirtualBox:~/Desktop/acvpproxy$ ./acvp-proxy -m "OpenSSL (64 bit)" --request

ACVPProxy (18:42:27) (tid0) Status: Register module OpenSSL (64 bit)
ACVPProxy (18:42:27) (tid0) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (18:42:27) (tid0) Status: Register module OpenSSL (64 bit)
ACVPProxy (18:42:27) (tid0) Status: Logging into ACVP server
ACVPProxy (18:42:47) (tid0) Error: No response data found
ACVPProxy (18:42:47) (tid0) Error: Failure to request testID 0 - module OpenSSL (64 bit) ((null))
ACVPProxy (18:42:47) (tid0) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (18:42:57) (tid0) Status: Logging into ACVP server
ACVPProxy (18:43:17) (tid0) Error: No response data found
ACVPProxy (18:43:17) (tid0) Error: Failure to request testID 0 - module OpenSSL (64 bit) ((null))
vm1@vm1-VirtualBox:~/Desktop/acvpproxy$ 

Any clue on this error

**Comment by smuellerDD** [comment]
Am Dienstag, 18. Mai 2021, 15:16:52 CEST schrieb shilpa-1992:

Hi shilpa,

> ***@***.***VirtualBox:~/Desktop/acvpproxy$ ./acvp-proxy -m "OpenSSL (64 bit)"
> --request
> 
> ACVPProxy (18:42:27) (tid0) Status: Register module OpenSSL (64 bit)
> ACVPProxy (18:42:27) (tid0) Status - TOTP MQ System: Requesting OTP value,
> waiting ... ACVPProxy (18:42:27) (tid0) Status: Register module OpenSSL (64
> bit) ACVPProxy (18:42:27) (tid0) Status: Logging into ACVP server
> ACVPProxy (18:42:47) (tid0) Error: No response data found
> ACVPProxy (18:42:47) (tid0) Error: Failure to request testID 0 - module
> OpenSSL (64 bit) ((null)) ACVPProxy (18:42:47) (tid0) Status - TOTP MQ
> System: Requesting OTP value, waiting ... ACVPProxy (18:42:57) (tid0)
> Status: Logging into ACVP server
> ACVPProxy (18:43:17) (tid0) Error: No response data found
> ACVPProxy (18:43:17) (tid0) Error: Failure to request testID 0 - module
> OpenSSL (64 bit) ((null)) ***@***.***VirtualBox:~/Desktop/acvpproxy$
> 
> Any clue on this error

verbose mode is your friend


Ciao
Stephan

**Comment by shilpa-1992** [comment]
Thank you
