### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#36]
Good Day 

I am getting below error while i try to request test vectors from demo server.

steps followed:
1. Created .csr to send to nist.
openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr
2. server.csr was Sent to nist and obtained totp seed and .crt
3.configured acvpproxy_conf.json as below
{
  "_COMMENT_tlsKeyFile":"Private key in PEM, DER or P12 format (optional when certificate is provided in P12 format with private key)",
  "tlsKeyFile":"pathto_above_generated_privatekey/server.key",
  "_COMMENT_tlsCertFile":"Certificate for key in PEM, DER, or P12 format",
  "tlsCertFile":"pathtocer/_Demo.cer",
  "_COMMENT_tlsKeyPasscode":"Passcode for private key - optional",
  "tlsKeyPasscode":"****",
  "_COMMENT":"Base64 Encoded TOTP seed data received from NIST",
  "totpSeedFile":"pathtototp/_totp.txt",
 
}

Error observed:
* Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
* ALPN, offering http/1.1
* unable to set private key file: 'pathto_above_generated_privatekey/server.key' type PEM
* Closing connection 0
ACVPProxy (22:34:32) (acvp-proxy) Warning - HTTP operation [lib/common/network_backend_curl.c:acvp_curl_http_common:481]: Curl HTTP operation failed with code 58 (Problem with the local SSL certificate)

Could you please help me in this.

Regards,

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 19.05.2021 um 22:49 -0700 schrieb shilpa-1992:
> Good Day 
> 
> I am getting below error while i try to request test vectors from demo
> server.
> 
> steps followed:
> 1. Created .csr to send to nist.
> openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr
> 2. server.csr was Sent to nist and obtained totp seed and .crt
> 3.configured acvpproxy_conf.json as below
> {
>   "_COMMENT_tlsKeyFile":"Private key in PEM, DER or P12 format (optional
> when certificate is provided in P12 format with private key)",
>   "tlsKeyFile":"pathto_above_generated_privatekey/server.key",
>   "_COMMENT_tlsCertFile":"Certificate for key in PEM, DER, or P12 format",
>   "tlsCertFile":"pathtocer/_Demo.cer",
>   "_COMMENT_tlsKeyPasscode":"Passcode for private key - optional",
>   "tlsKeyPasscode":"****",
>   "_COMMENT":"Base64 Encoded TOTP seed data received from NIST",
>   "totpSeedFile":"pathtototp/_totp.txt",
>  
> }
> 
> Error observed:
> * Connected to demo.acvts.nist.gov (52.204.191.193) port 443 (#0)
> * ALPN, offering http/1.1
> * unable to set private key file:
> 'pathto_above_generated_privatekey/server.key' type PEM
> * Closing connection 0
> ACVPProxy (22:34:32) (acvp-proxy) Warning - HTTP operation
> [lib/common/network_backend_curl.c:acvp_curl_http_common:481]: Curl HTTP
> operation failed with code 58 (Problem with the local SSL certificate)
> 
> Could you please help me in this.
> 

See README on the key file name extensions and the implied key types.

Ciao
Stephan

> Regards,
> 
> 
> 
>
