### ISSUE TITLE
Request command

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#37]
Good day !

I need to test only for safeprimes (keygen , key ver) , kas-ECC ,KAS-FFC  (Sp800-56Ar3.
How can i request in Demo server for these test vectors.

acvp-proxy -m <cryptomodule> --request 
not sure what is to be filled up in <cryptomodule> to get above mentioned test vectors alone.

Regards,

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 20.05.2021 um 22:56 -0700 schrieb shilpa-1992:
> Good day !
> 
> I need to test only for safeprimes (keygen , key ver) , kas-ECC ,KAS-FFC 
> (Sp800-56Ar3.
> How can i request in Demo server for these test vectors.
> 
> acvp-proxy -m <cryptomodule> --request 
> not sure what is to be filled up in <cryptomodule> to get above mentioned
> test vectors alone.

Check README.md "Module Instantiation Configuration", focus on
'implementations' ("Implementation definition").

Add/update a respective cipher definition according to "Addition of New Cipher
Implementation Definitions".

> 
> Regards,
> 
>

**Comment by shilpa-1992** [comment]
How to 

1.Register the meta information about the module with the ACVP server, including vendor information, module information and operational environment information.

2.Request the publication of the completed ACVP testing cycle to obtain an ACVP certificate.

Regards,

**Comment by smuellerDD** [comment]
Am Montag, dem 24.05.2021 um 05:17 -0700 schrieb shilpa-1992:
> How to 
> 
> 1.Register the meta information about the module with the ACVP server,
> including vendor information, module information and operational environment
> information.
> 
> 2.Request the publication of the completed ACVP testing cycle to obtain an
> ACVP certificate.

To both, see README.md "Test Publication Phase"
> 
> Regards,
>
