### ISSUE TITLE
Certificate Request

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpproxy#38]
I tried requesting for certificate from the proxy client with below command and it did not alter the state “Passed” to “Submitted For Approval” at NIST end, and  the Request ID not activated, making it visible and ready for review/approval. (I have all the test requestes in PASSED state)

acvp-proxy  -m "cryptomodule" --publish

I believe in Demo, the approval would happen instantly since everything is set to be auto approved. Could you please suggest me how to request for certificate.

Below error is seen 

acvp@totp:~/hslee/acvpproxy$ ./acvp-proxy --publish --testid 180252
ACVPProxy (22:05:02) (acvp-proxy) Status: Publishing testID 180252
ACVPProxy (22:05:02) (acvp-proxy) Status: Fetch request for ID 21702
ACVPProxy (22:05:02) (acvp-proxy) Status: Request ID not obtained, request pending - please query the request again once NIST approved the request. The request ID that NIST needs to approve is 21702

I checked with Arnold Jason of NIST he said " I think is happening is that you haven’t yet requested a certification from the acvp client. A certify request would alter the state on our end from “Passed” to “Submitted For Approval”, and that would activate the Request ID, making it visible and ready for review/approval. In Demo, the approval would happen instantly since everything is set to be auto approved. So my advice is to have a look back at your process/steps and see what might be missing from the certification request standpoint"

Please help

Regards,

**Comment by shilpa-1992** [comment]
what can be done this error is shown

"ACVPProxy (07:19:21) (acvp-proxy) Verbose [acvp/definition.c:acvp_match_def_v1:481]: Crypto definition for testID 180630 for current search does not match with old search
'

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 27.05.2021 um 07:20 -0700 schrieb shilpa-1992:
> what can be done this error is shown
> 
> "ACVPProxy (07:19:21) (acvp-proxy) Verbose
> [acvp/definition.c:acvp_match_def_v1:481]: Crypto definition for testID
> 180630 for current search does not match with old search

You fiddled manually in the database or renamed entries in the
module_definition/ directory and now the definition_reference.json does not
match any more.

If you rename aspects, use the --rename-* options.


> '
>

**Comment by shilpa-1992** [comment]
Thank you for the support.

Regards,
