### ISSUE TITLE
Error in downloading sample vectors:

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [smuellerDD/acvpproxy#39]
Hi 

I have downloaded the request vectors from server using command :

1.7.0$ ./acvp-proxy -m "OpenSSL (64 bit) (SHA_AVX2)" --request
ACVPProxy (23:32:01) (tid0) Status: Register module OpenSSL (64 bit) (SHA_AVX2)
ACVPProxy (23:32:01) (tid0) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (23:32:01) (tid0) Status: Logging into ACVP server
ACVPProxy (23:39:38) (vid610600) Status: (Re)Try testID 186284 / vsID 610600 (41 / 42 done)
ACVPProxy (23:40:12) (vid610600) Status: (Re)Try testID 186284 / vsID 610600 (41 / 42 done)
ACVPProxy (23:40:45) (vid610600) Status: (Re)Try testID 186284 / vsID 610600 (41 / 42 done)
ACVPProxy (23:41:18) (vid610600) Status: (Re)Try testID 186284 / vsID 610600 (41 / 42 done)
ACVPProxy (23:41:51) (vid610600) Status: (Re)Try testID 186284 / vsID 610600 (41 / 42 done)
ACVPProxy (23:41:54) (vid610600) Status: Tests obtained for testID 186284 / vsID 610600 (42 / 42 done)

I downloaded the sample files server using command :

/acvp_proxy_v2/acvpproxy-1.7.0$ ./acvp-proxy -m "OpenSSL (64 bit) (SHA_AVX2)" --testid  186284  --sample
ACVPProxy (00:05:51) (vid610616) Status: (Re)Try testID 186284 / vsID 610616 (0 / 0 done)
ACVPProxy (00:05:51) (vid610594) Status: (Re)Try testID 186284 / vsID 610594 (0 / 0 done)
ACVPProxy (00:05:51) (vid610591) Status: (Re)Try testID 186284 / vsID 610591 (0 / 0 done)
ACVPProxy (00:05:52) (vid610584) Status: (Re)Try testID 186284 / vsID 610584 (0 / 0 done)
ACVPProxy (00:05:52) (vid610580) Status: (Re)Try testID 186284 / vsID 610580 (0 / 0 done)

But the testvector-expected.json file contains below error : 

{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "00-d7cd5a439fb3214581aea1de5bccddd0-d100c0a8482bf44c-00"
}

Thanks,
Nag

**Comment by smuellerDD** [comment]
Am Dienstag, dem 29.06.2021 um 00:37 -0700 schrieb Nagarjun:
> Hi 
> 
> I have downloaded the request vectors from server using command :
> 
> 1.7.0$ ./acvp-proxy -m "OpenSSL (64 bit) (SHA_AVX2)" --request
> ACVPProxy (23:32:01) (tid0) Status: Register module OpenSSL (64 bit)
> (SHA_AVX2)
> ACVPProxy (23:32:01) (tid0) Status - TOTP MQ System: Requesting OTP value,
> waiting ...
> ACVPProxy (23:32:01) (tid0) Status: Logging into ACVP server
> ACVPProxy (23:39:38) (vid610600) Status: (Re)Try testID 186284 / vsID 610600
> (41 / 42 done)
> ACVPProxy (23:40:12) (vid610600) Status: (Re)Try testID 186284 / vsID 610600
> (41 / 42 done)
> ACVPProxy (23:40:45) (vid610600) Status: (Re)Try testID 186284 / vsID 610600
> (41 / 42 done)
> ACVPProxy (23:41:18) (vid610600) Status: (Re)Try testID 186284 / vsID 610600
> (41 / 42 done)
> ACVPProxy (23:41:51) (vid610600) Status: (Re)Try testID 186284 / vsID 610600
> (41 / 42 done)
> ACVPProxy (23:41:54) (vid610600) Status: Tests obtained for testID 186284 /
> vsID 610600 (42 / 42 done)
> 
> I downloaded the sample files server using command :
> 
> /acvp_proxy_v2/acvpproxy-1.7.0$ ./acvp-proxy -m "OpenSSL (64 bit)
> (SHA_AVX2)" --testid  186284  --sample
> ACVPProxy (00:05:51) (vid610616) Status: (Re)Try testID 186284 / vsID 610616
> (0 / 0 done)
> ACVPProxy (00:05:51) (vid610594) Status: (Re)Try testID 186284 / vsID 610594
> (0 / 0 done)
> ACVPProxy (00:05:51) (vid610591) Status: (Re)Try testID 186284 / vsID 610591
> (0 / 0 done)
> ACVPProxy (00:05:52) (vid610584) Status: (Re)Try testID 186284 / vsID 610584
> (0 / 0 done)
> ACVPProxy (00:05:52) (vid610580) Status: (Re)Try testID 186284 / vsID 610580
> (0 / 0 done)
> 
> 
> But the testvector-expected.json file contains below error : 
> 
> {
>   "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
>   "title": "Not Found",
>   "status": 404,
>   "traceId": "00-d7cd5a439fb3214581aea1de5bccddd0-d100c0a8482bf44c-00"
> }
> 
That does not work as you need to request the sample during initial
registration, i.e. --request --sample

Ciao
Stephan
