### ISSUE TITLE
How to supply algorithm parameters to acvp-proxy

### ISSUE THREAD

**Issue by sckoehler** [smuellerDD/acvpproxy#40]
I have read and re-read the README.md, but I'm having trouble figuring out how you supply algorithm parameters to acvp-proxy so the demo server knows what samples or vectors to send back.  Presumably, there is some place I need to present json files like the following:

>  [
>   {
>     "acvVersion": "1.0"
>   },
>   {
>     "algorithms": [
>       {
>         "algorithm": "ACVP-AES-GCM",
>         "revision": "1.0",
>         "prereqVals": [
>           {
>             "algorithm": "AES",
>             "valValue": "same"
>           },
> ...
> 

I would very much appreciate some help in figuring out this point.

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 29.07.2021 um 09:42 -0700 schrieb sckoehler:
> I have read and re-read the README.md, but I'm having trouble figuring out
> how you supply algorithm parameters to acvp-proxy so the demo server knows
> what samples or vectors to send back.  Presumably, there is some place I
> need to present json files like the following:
> 
> >  [
> >   {
> >     "acvVersion": "1.0"
> >   },
> >   {
> >     "algorithms": [
> >       {
> >         "algorithm": "ACVP-AES-GCM",
> >         "revision": "1.0",
> >         "prereqVals": [
> >           {
> >             "algorithm": "AES",
> >             "valValue": "same"
> >           },
> > ...
> > 
> 
> I would very much appreciate some help in figuring out this point.

The proxy has 2 areas: the first is the actual cipher definition. A trivial
example is in lib/module_definition/definition_impl_nettle.c. A more complex
is the openssl definition. Those are maintained in C as they are intended to
hardly change.

A second aspect is the volatile data like module name, version, vendor, and
other meta data. That is defined in module_definition/. Note, all permutations
of configurations for a given module in there are applied. Thus, if you have
one vendor, one module_info, but two OE definitions, you duplicated your
modules. If you have, say, now two instead of one module_info you quadrupled
the modules.

Ciao
Stephan
> 
>

**Comment by sckoehler** [comment]
Stephan,

Thanks very much.  I was coming to this conclusion yesterday, after spending a lot of time in the code.  It sounds like if I wanted to adapt acvpproxy to a new crypto module, say Bouncy Castle, that it would require code changes, unless that module happened to overlap the capabilities of an existing module and could pretend to be that module.

**Comment by smuellerDD** [comment]
Am Freitag, dem 30.07.2021 um 07:17 -0700 schrieb sckoehler:
> Stephan,
> 
> Thanks very much.  I was coming to this conclusion yesterday, after spending
> a lot of time in the code.  It sounds like if I wanted to adapt acvpproxy to
> a new crypto module, say Bouncy Castle, that it would require code changes,
> unless that module happened to overlap the capabilities of an existing
> module and could pretend to be that module.
> 

Yes, that is the concept of it: add another C file with the algorithm
definitions. Those definitions are, however, more like a config file for most
algos considering the extensive use of macros and pre-defined algos.

Ciao
Stephan

**Comment by sckoehler** [comment]
Stephen,

Thanks very much, again.  

I have (I hope) a final question.  Even with the sample module definitions I have been unable to fetch vectors.  No matter what I have tried, I get the error **No algorithms were present within the algorithms property**.  I have tried both proxy.sh and raw acvp-proxy.  Here's an example:

> ./acvp-proxy -m "Crypto for ACVPProxy" --list
> Vendor Name |                   OE |     Proc |          Module Name | Version | vsIDs
> atsec corp. | macOS Catalina 10.15 | i7-5557U | Crypto for ACVPProxy |     1.0 |     0
> atsec corp. |            Fedora 32 | i7-5557U | Crypto for ACVPProxy |     1.0 |     0
> atsec corp. |            Fedora 30 |       i7 | Crypto for ACVPProxy |     1.0 |     0
> atsec corp. | macOS Catalina 10.15 | i7-5557U | Crypto for ACVPProxy |     2.0 |     0
> atsec corp. |            Fedora 32 | i7-5557U | Crypto for ACVPProxy |     2.0 |     0
> atsec corp. |            Fedora 30 |       i7 | Crypto for ACVPProxy |     2.0 |     0
> ======================================================================================
> Expected numbers of vsIDs for listed definitions: 0

> ./acvp-proxy -m "Crypto for ACVPProxy" --request
> ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> ACVPProxy (10:03:59) (tid0) Status - TOTP MQ System: Requesting OTP value, waiting ...
> ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> ACVPProxy (10:03:59) (tid0) Status: Logging into ACVP server
> ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module Crypto for ACVPProxy ((null))
> ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module Crypto for ACVPProxy ((null))
> ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module Crypto for ACVPProxy ((null))
> ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module Crypto for ACVPProxy ((null))
> ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module Crypto for ACVPProxy ((null))
> ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module Crypto for ACVPProxy ((null))

The following error is invariably returned from the ACVP demo server:

> [
>   {
>     "acvVersion": "1.0"
>   },
>   {
>     "error": "Validation error(s) on JSON payload.",
>     "context": [
>       "No algorithms were present within the algorithms property."
>     ]
>   }
> ]

Can you point me in the right direction? I have tried looking in the code for what data feeds into the algorithms property in the request, but have not yet succeeded in figuring this out.

**Comment by smuellerDD** [comment]
Am Freitag, dem 30.07.2021 um 08:08 -0700 schrieb sckoehler:
> Stephen,
> 
> Thanks very much, again.  
> 
> I have (I hope) a final question.  Even with the sample module definitions I
> have been unable to fetch vectors.  No matter what I have tried, I get the
> error **No algorithms were present within the algorithms property**.  I have
> tried both proxy.sh and raw acvp-proxy.  Here's an example:
> 
> > ./acvp-proxy -m "Crypto for ACVPProxy" --list
> > Vendor Name |                   OE |     Proc |          Module Name |
> > Version | vsIDs
> > atsec corp. | macOS Catalina 10.15 | i7-5557U | Crypto for ACVPProxy |    
> > 1.0 |     0
> > atsec corp. |            Fedora 32 | i7-5557U | Crypto for ACVPProxy |    
> > 1.0 |     0
> > atsec corp. |            Fedora 30 |       i7 | Crypto for ACVPProxy |    
> > 1.0 |     0
> > atsec corp. | macOS Catalina 10.15 | i7-5557U | Crypto for ACVPProxy |    
> > 2.0 |     0
> > atsec corp. |            Fedora 32 | i7-5557U | Crypto for ACVPProxy |    
> > 2.0 |     0
> > atsec corp. |            Fedora 30 |       i7 | Crypto for ACVPProxy |    
> > 2.0 |     0

Not fully sure where you got this from. I have:

$ ./acvp-proxy -m "Crypto for ACVPProxy" -f -l
Vendor Name |                   OE |     Proc |                      Module
Name | Version | vsIDs
atsec corp. |            Fedora 32 | i7-5557U | Crypto for ACVPProxy (Generic
C) |     2.0 |    12
atsec corp. | macOS Catalina 10.15 | i7-5557U | Crypto for ACVPProxy (Generic
C) |     2.0 |    12
==============================================================================
====================
Expected numbers of vsIDs for listed definitions: 24

Now, let us just focus on one:

$ ./acvp-proxy -m "Crypto for ACVPProxy" -f -e "Fedora 32" -l
Vendor Name |        OE |     Proc |                      Module Name |
Version | vsIDs
atsec corp. | Fedora 32 | i7-5557U | Crypto for ACVPProxy (Generic C) |    
2.0 |    12
==============================================================================
=========
Expected numbers of vsIDs for listed definitions: 12

Now let us check what the proxy would send to the server:

$ ./acvp-proxy -m "Crypto for ACVPProxy" -f -e "Fedora 32" --request --dump-
register
ACVPProxy (17:35:03) (tid0) Status: Register module Crypto for ACVPProxy
(Generic C)
[
  {
    "acvVersion":"1.0"
  },
  {
    "isSample":false,
    "operation":"register",
    "certificateRequest":"no",
    "debugRequest":"yes",
    "production":"no",
    "encryptAtRest":"yes",
    "algorithms":[
      {
        "revision":"1.0",
        "algorithm":"SHA2-256",
        "inBit":false,
        "inEmpty":true,
        "messageLength":[
          {
            "min":0,
            "max":65536,
            "increment":8
          }
        ]
      },
      {
        "revision":"1.0",
        "algorithm":"SHA2-512",
        "inBit":false,
        "inEmpty":true,
        "messageLength":[
          {
            "min":0,
            "max":65536,
            "increment":8
          }
        ]
      },
      {
        "revision":"1.0",
        "algorithm":"SHA3-224",
        "inBit":false,
        "inEmpty":true,
        "messageLength":[
          {
            "min":0,
            "max":65536,
            "increment":8
          }
        ]
      },

...


Now let us do it:

$ ./acvp-proxy -m "Crypto for ACVPProxy" -f -e "Fedora 32" --request
ACVPProxy (17:35:32) (tid0) Status: Register module Crypto for ACVPProxy
(Generic C)
ACVPProxy (17:35:32) (tid0) Status - TOTP MQ System: Requesting OTP value,
waiting ...
ACVPProxy (17:35:33) (tid0) Status: Logging into ACVP server
ACVPProxy (17:35:35) (vid655941) Status: (Re)Try testID 193172 / vsID 655941
(0 / 12 done)
ACVPProxy (17:35:35) (vid655942) Status: (Re)Try testID 193172 / vsID 655942
(0 / 12 done)
...

> > ============================================================================
> > ==========
> > Expected numbers of vsIDs for listed definitions: 0
> 
> > ./acvp-proxy -m "Crypto for ACVPProxy" --request
> > ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> > ACVPProxy (10:03:59) (tid0) Status - TOTP MQ System: Requesting OTP value,
> > waiting ...
> > ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> > ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> > ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> > ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> > ACVPProxy (10:03:59) (tid0) Status: Register module Crypto for ACVPProxy
> > ACVPProxy (10:03:59) (tid0) Status: Logging into ACVP server
> > ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module
> > Crypto for ACVPProxy ((null))
> > ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module
> > Crypto for ACVPProxy ((null))
> > ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module
> > Crypto for ACVPProxy ((null))
> > ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module
> > Crypto for ACVPProxy ((null))
> > ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module
> > Crypto for ACVPProxy ((null))
> > ACVPProxy (10:04:00) (tid0) Error: Failure to request testID 0 - module
> > Crypto for ACVPProxy ((null))
> 
> The following error is invariably returned from the ACVP demo server:
> 
> > [
> >   {
> >     "acvVersion": "1.0"
> >   },
> >   {
> >     "error": "Validation error(s) on JSON payload.",
> >     "context": [
> >       "No algorithms were present within the algorithms property."
> >     ]
> >   }
> > ]
> 
> Can you point me in the right direction? I have tried looking in the code for
> what data feeds into the algorithms property in the request, but have not yet
> succeeded in figuring this out.
>

**Comment by sckoehler** [comment]
Interesting.  My sources are up to date on master. I think I know what happened though.  I did a `make clean` and `make', and things now work like they did for you. I then did a `make binarchive` and it is broken again. It's possible that the following error, which I ignored, left the build in an inconsistent state:

> lib/common/network_backend_curl.c:420:3: warning: call to ‘_curl_easy_setopt_err_postfields’ declared with attribute warning: curl_easy_setopt expects a 'void *' or 'char *' argument for this option
>    CURL_CKINT(curl_easy_setopt(curl, CURLOPT_POSTFIELDS,
>    ^
> ln acvp-proxy esvp-proxy
> ln: failed to create hard link 'esvp-proxy': File exists
> Makefile:214: recipe for target 'EX-acvp-proxy' failed
> make: *** [EX-acvp-proxy] Error 1
> 

Anyway, I'm back on track.  Thanks very much for the help.

**Comment by smuellerDD** [comment]
Am Freitag, dem 30.07.2021 um 08:58 -0700 schrieb sckoehler:
> Interesting.  My sources are up to date on master. I think I know what
> happened though.  I did a `make clean` and `make', and things now work like
> they did for you. I then did a `make binarchive` and it is broken again.

Aha, the binarchive - this compiles the mentioned C definitions into separate
shared libraries which are to be loaded during invocation of the acvp-proxy
command with --proxy-extension.

But this would be a hassle to do manually - thus the helper/proxy.sh comes
into play. This does all magically for you. The reason for compiling the SOs
is to allow using a new "protocol implementation" provided with the acvp-proxy
binary on older cipher definitions.

All in all, only use the binarchive together with the proxy.sh command.
Otherwise, use the static binary.

> It's possible that the following error, which I ignored, left the build in
> an inconsistent state:
> 
> > lib/common/network_backend_curl.c:420:3: warning: call to
> > ‘_curl_easy_setopt_err_postfields’ declared with attribute warning:
> > curl_easy_setopt expects a 'void *' or 'char *' argument for this option
> >    CURL_CKINT(curl_easy_setopt(curl, CURLOPT_POSTFIELDS,
> >    ^
> > ln acvp-proxy esvp-proxy
> > ln: failed to create hard link 'esvp-proxy': File exists
> > Makefile:214: recipe for target 'EX-acvp-proxy' failed
> > make: *** [EX-acvp-proxy] Error 1

Not sure what goes on, but the binarchive is my default method for the
production operation with the proxy.sh script.

Ciao
Stephan
