### ISSUE TITLE
./proxy.sh get: error accessing seed file certs + ACVP library was not yet initialized

### ISSUE THREAD

**Issue by Gunmetal-61** [smuellerDD/acvpproxy#41]
I am trying to follow the README and get acvpproxy working with the `./proxy.sh get` command.  This is my acvpproxy_conf.json file:  

```
{
  "_COMMENT_tlsCaBundle":"CA key bundle in PEM or DER format - on macOS DER is mandatory",
  "tlsCaBundle":"certs/digitcert_bundle.pem",
  "_COMMENT_tlsKeyFile":"Private key in PEM, DER or P12 format (optional when certificate is provided in P12 format with private key)",
  "tlsKeyFile":"certs/ESVDemo.key",
  "_COMMENT_tlsCertFile":"Certificate for key in PEM, DER, or P12 format",
  "tlsCertFile":"certs/ESVDemo.cer",
  "_COMMENT":"Base64 Encoded TOTP seed data received from NIST",
  "totpSeedFile":"certs/ESVDemo_totp.txt",
}
```

I get these two outputs in repeating, alternating order to the same aforementioned command:

```
ubuntu-VirtualBox:~/Documents/Panther-Crypto-Verif/mxl_panther_sdk/app/nist_test_new$ ./proxy.sh get
ACVPProxy (20:58:12) (acvp-proxy) Error: Error accessing seed file certs/MaxLinear_Mitchell_Wu_ESVDemo_totp.txt (-2)
ACVPProxy (20:58:12) (acvp-proxy) Error: ACVP library was not yet initialized
Command invocation returned 2
Now go out and sip some coffee and re-invoke command at a later time of your choice.
There is no network operation happening until you re-invoke the command allowing you to go about your business without considering at the ACVP connection

ubuntu-VirtualBox:~/Documents/Panther-Crypto-Verif/mxl_panther_sdk/app/nist_test_new$ ./proxy.sh get
ACVPProxy (20:58:15) (acvp-proxy) Error: Error accessing seed file certs/MaxLinear_Mitchell_Wu_ESVDemo_totp.txt (-2)
ACVPProxy (20:58:15) (acvp-proxy) Error: ACVP library was not yet initialized
Command invocation returned 2

find: ‘./test-vectors/testvectors’: No such file or directory
Archive ./test-vectors/testvectors and send this archive to vendor to process it with the ACVP Parser.
        tar -C ./test-vectors/ -czf testvectors.tar.gz testvectors/

After processing the archive, the vendor shall return the archive from the following command:
        tar -czf results.tar.gz $(find testvectors/ -name testvector-response.json)

Unpack the received responses with the following command:
        tar -C ./test-vectors/ -xzf results.tar.gz
```

The first error regarding the seed file cert (TOTP) leads me to wonder if either the format of the file I'm sending in is not compatible, or if the TOTP seed is incorrect.  Is there something with the content of my credentials?

The second issue I suspect to be related to a part of the GitHub README I don't quite understand:  [Module Instantiation Configuration](https://github.com/smuellerDD/acvpproxy#module-instantiation-configuration), particularly [Operational Environment Configuration](https://github.com/smuellerDD/acvpproxy#module-instantiation-configuration).  In the acvpproxy/module_definitions/acvpproxy/oe, I only see JSON config files for Fedora and macOS distributions, not Ubuntu as I am running.  But I don't know what this is for.  Can anyone explain any part of this to me?

Thanks.

**Comment by smuellerDD** [comment]
Am Donnerstag, 12. August 2021, 06:22:09 CEST schrieb Mitchell Wu:

Hi Mitchell,

> I am trying to follow the README and get acvpproxy working with the
> `./proxy.sh get` command.  This is my acvpproxy_conf.json file:  
 
> ```
> {
>   "_COMMENT_tlsCaBundle":"CA key bundle in PEM or DER format - on macOS DER
> is mandatory",
 "tlsCaBundle":"certs/digitcert_bundle.pem",
>   "_COMMENT_tlsKeyFile":"Private key in PEM, DER or P12 format (optional
> when certificate is provided in P12 format with private key)",
> "tlsKeyFile":"certs/ESVDemo.key",
>   "_COMMENT_tlsCertFile":"Certificate for key in PEM, DER, or P12 format",
>   "tlsCertFile":"certs/ESVDemo.cer",
>   "_COMMENT":"Base64 Encoded TOTP seed data received from NIST",
>   "totpSeedFile":"certs/ESVDemo_totp.txt",
> }
> ```
> 
> I get these two outputs in repeating, alternating order to the same
> aforementioned command:
 
> ```
> ubuntu-VirtualBox:~/Documents/Panther-Crypto-Verif/mxl_panther_sdk/app/nist_
> test_new$ ./proxy.sh get
 ACVPProxy (20:58:12) (acvp-proxy) Error: Error
> accessing seed file certs/MaxLinear_Mitchell_Wu_ESVDemo_totp.txt (-2)

This error means that the MaxLinear_Mitchell_Wu_ESVDemo_totp.txt cannot be 
opened with error ENOENT (file not found).

Note, when you use the proxy.sh, you probably want an absolute path name.

Ciao
Stephan

**Comment by Gunmetal-61** [comment]
Thank you Stephan.  Yes, I wasn't exactly sure what format the totp.txt file should be set to.  The instructions weren't exactly clear to me.

In the meantime however, I did manage to get libacvp (which we were working with initially) up and running properly, so we will be moving forward with that library and keeping your suggestion in mind.  Thank you for the help.
