### ISSUE TITLE
Fetching Vectors from the ACVP Proxy Error

### ISSUE THREAD

**Issue by DanaLanza** [smuellerDD/acvpproxy#46]
Hello,

I am encountering the following error when i use the command "./acvp-proxy -m "OpenSSL (64 bit) (AES_C)" --request -vvv"
I am using Ubuntu 18.04.6 LTS and the OpenSSL 1.1.1 version.
I would greatly appreciate your help resolving this error. Thank you.

* Connection #0 to host demo.acvts.nist.gov left intact
ACVPProxy (15:16:07) (tid0) Warning - HTTP operation: Unable to HTTP POST data for URL https://demo.acvts.nist.gov:443/acvp/v1/testSessions: 400
ACVPProxy (15:16:07) (tid0) Verbose: Process following server response: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "ctrDRBG-1.0: Invalid Nonce Range for AES-128 supplied: 64,64.  Values were not between 0 and 0"
    ]
  }
]
ACVPProxy (15:16:07) (tid0) Verbose - HTTP operation: ACVP server return code: test response received, verdict pending
ACVPProxy (15:16:07) (tid0) Error: Server error response: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "ctrDRBG-1.0: Invalid Nonce Range for AES-128 supplied: 64,64.  Values were not between 0 and 0"
    ]
  }
]
ACVPProxy (15:16:07) (tid0) Verbose - File backend: data written for testID 0 to file register_response-20240425_15-16-07.debug
ACVPProxy (15:16:07) (tid0) Error: Failure to request testID 0 - module OpenSSL (64 bit) (AES_C) (AES_C)
ACVPProxy (15:16:07) (tid0) Verbose: All vsIDs processed for testID 0
ACVPProxy (15:16:07) (tid0) Verbose - Threading support: Thread 0 completed
ACVPProxy (15:16:07) (acvp-proxy) Warning: At least one thread returned an error: -1000
ACVPProxy (15:16:07) (signal0) Verbose - Signal handler: thread terminated
ACVPProxy (15:16:07) (totp0) Verbose - TOTP MQ System: terminate server
ACVPProxy (15:16:07) (acvp-proxy) Verbose - Threading support: Thread 0 terminated
ACVPProxy (15:16:07) (acvp-proxy) Verbose - Threading support: Thread 512 killed
ACVPProxy (15:16:07) (acvp-proxy) Verbose - Threading support: Thread 514 killed

**Comment by smuellerDD** [comment]
Am Donnerstag, 25. April 2024, 23:32:19 MESZ schrieb DanaLanza:

Hi DanaLanza,

fix applied.

Ciao
Stephan

**Comment by DanaLanza** [comment]
Hi Stephan,

It's resolved now. Thank you so much Stephan!

Sincerely,
Dana Lanza
