### ISSUE TITLE
AES-256 Test Vectors

### ISSUE THREAD

**Issue by DanaLanza** [smuellerDD/acvpproxy#47]
Hi Stephan,

I greatly appreciate all your help and resolving my issues quickly. 
Is there a command to obtain the test vectors from the ACVP Proxy to only output AES-256 test vectors? Or do I have to test the AES-128 vectors as well to get the certification? Thank you.

Sincerely,
Dana Lanza

**Comment by smuellerDD** [comment]
Am Mittwoch, 1. Mai 2024, 22:46:56 MESZ schrieb DanaLanza:

Hi DanaLanza,

> Hi Stephan,
> 
> I greatly appreciate all your help and resolving my issues quickly.
> Is there a command to obtain the test vectors from the ACVP Proxy to only
> output AES-256 test vectors? Or do I have to test the AES-128 vectors as
> well to get the certification? Thank you.
> 
> Sincerely,
> Dana Lanza

#define GENERIC_AES_ALGO_GEN(x)						\
	.type = DEF_ALG_TYPE_SYM,					\
	.algo.sym.algorithm = x,					\
	.algo.sym.direction = DEF_ALG_SYM_DIRECTION_ENCRYPTION |	\
			      DEF_ALG_SYM_DIRECTION_DECRYPTION,		\
	.algo.sym.keylen = DEF_ALG_SYM_KEYLEN_128 |			\
			   DEF_ALG_SYM_KEYLEN_192 |			\
			   DEF_ALG_SYM_KEYLEN_256

/**
 * @brief AES CBC definition.
 *
 * Cipher definition properties
 *	* encryption / decryption
 *	* key sizes: 128, 192, 256
 * 	* arbitrary plaintext length
 */
#define GENERIC_AES_CBC							\
	{								\
	GENERIC_AES_ALGO_GEN(ACVP_CBC),					\
	DEF_ALG_DOMAIN(.algo.sym.ptlen, 128, 65536, 128),		\
	.algo.sym.ivlen = { 128, },					\
	}


change the .algo.sym.keylen

Ciao
Stephan

**Comment by DanaLanza** [comment]
Thank you again Stephan!! I will resolve this issue.

**Comment by DanaLanza** [comment]
Hi Stephan, 
I am trying to requests test vectors that are only AES-256 ECB mode. I commented out all the defines except the '#define GENERIC_AES_ECB' in the defenition_impl_common.h file, and I get the error for all the other AES modes I commented out "lib/module_implementations/definition_impl_leancrypto.c:28:20: error: ‘GENERIC_AES_CBC’ undeclared here (not in a function); did you mean ‘GENERIC_AES_CCM’?
#define LC_AES_CBC GENERIC_AES_CBC
                    ^
lib/module_implementations/definition_impl_leancrypto.c:293:2: note: in expansion of macro ‘LC_AES_CBC’
  LC_AES_CBC,
  ^~~~~~~~~~
lib/module_implementations/definition_impl_leancrypto.c:29:20: error: ‘GENERIC_AES_CTR’ undeclared here (not in a function); did you mean ‘GENERIC_AES_CBC’?
#define LC_AES_CTR GENERIC_AES_CTR
                    ^
lib/module_implementations/definition_impl_leancrypto.c:294:2: note: in expansion of macro ‘LC_AES_CTR’". Is this the right way to do this?
I greatly appreciate all your help.

**Comment by smuellerDD** [comment]
Am Donnerstag, 23. Mai 2024, 19:52:49 MESZ schrieb DanaLanza:

Hi DanaLanza,

> Hi Stephan,
> I am trying to requests test vectors that are only AES-256 ECB mode. I
> commented out all the defines except the '#define GENERIC_AES_ECB' in the
> defenition_impl_common.h file, and I get the error for all the other AES
> modes I commented out
> "lib/module_implementations/definition_impl_leancrypto.c:28:20: error:
> ‘GENERIC_AES_CBC’ undeclared here (not in a function); did you mean
> ‘GENERIC_AES_CCM’? #define LC_AES_CBC GENERIC_AES_CBC
>                     ^
> lib/module_implementations/definition_impl_leancrypto.c:293:2: note: in
> expansion of macro ‘LC_AES_CBC’ LC_AES_CBC,
>   ^~~~~~~~~~
> lib/module_implementations/definition_impl_leancrypto.c:29:20: error:
> ‘GENERIC_AES_CTR’ undeclared here (not in a function); did you mean
> ‘GENERIC_AES_CBC’? #define LC_AES_CTR GENERIC_AES_CTR
>                     ^
> lib/module_implementations/definition_impl_leancrypto.c:294:2: note: in
> expansion of macro ‘LC_AES_CTR’". Is this the right way to do this? I
> greatly appreciate all your help.

Hm, so you removed the definition of a large number of symbols. The you 
compile and you wonder why the compiler screams that the removed symbols are 
missing?

I think you wanted to remove the *usage* of the symbols from your 
definition_impl....c file.


Ciao
Stephan

**Comment by DanaLanza** [comment]
I realized right after that those lines should not be commented out. I apologize for that. I was able to get all AES-256 ECB test vectors by changing it to: 
#define GENERIC_AES_ALGO_GEN(x)                     \
    .type = DEF_ALG_TYPE_SYM,                   \
    .algo.sym.algorithm = ACVP_ECB,                 \
    .algo.sym.direction = DEF_ALG_SYM_DIRECTION_ENCRYPTION |    \
                  DEF_ALG_SYM_DIRECTION_DECRYPTION,     \
    .algo.sym.keylen = DEF_ALG_SYM_KEYLEN_256
Thank you.
