### ISSUE TITLE
Project Contributions?

### ISSUE THREAD

**Issue by Rasstrelnikov** [smuellerDD/acvpproxy#5]
Hi Stephan,

Firstly, thank you for making this project and also making it open source (this as well as the parser)! Secondly, are you looking for any contributions? 

Thanks,
Heidi Hart (Penumbra Security)

**Comment by smuellerDD** [comment]
Am Donnerstag, 10. Januar 2019, 22:36:23 CET schrieb Rasstrelnikov:

Hi Heidi,

> Hi Stephan,
> 
> Firstly, thank you for making this project and also making it open source
> (this as well as the parser)! Secondly, are you looking for any
> contributions?

Yes, always :-)

As you see from my other GitHub projects, I am a supporter of the Open Source 
idea.

Ciao
Stephan

**Comment by Rasstrelnikov** [comment]
Hi Stephan,

Good to know, thank you!

Best,
Heidi
