### ISSUE TITLE
Procedure to add a new vendor module to ACVP Proxy

### ISSUE THREAD

**Issue by jramage77** [smuellerDD/acvpproxy#7]
Hi - although I've reviewed the README file including the section on implementations, I have additional questions on how to add a new vendor module to Proxy. Being a lab, we typically we would use the CAVS tool to specify module algorithms/modes, generate and verify vectors then submit to CAVP.

With the new ACVP server and the Proxy, how do we build and install a new vendor module implementation? I'm trying to fully understand this procedure so we can estimate time required to fully implement, test and submit vendor module algorithms.

Are these the steps?

  A - MODULE IMPLEMENTATION: - create a new C program for vendor module e.g. similar to "definition_impl_openssl.c" with cipher defs specification based on module capabilities
	
  B - MODULE DEFINITION: - create new module definitions directories: module_info, oe and vendor files. 
  
  C - Request vector sets for module implementation
  
  D - Obtain response vectors - use the Parser to convert json to from text (a la CAVS) and send to vendor for harness testing to produce response vectors
  
  E - Verify response vectors and submit - ANY ADDITIONAL PROGRAMMING REQUIRED FOR NEW MODULE IMPLEMENTATION???

Any additional insights and guidance would be appreciated.

**Comment by acronymhaterheidi** [comment]
I am not an expert but I think I may be able to clarify a few things based on my own understanding:

I believe that the parser does not convert json to and from text (the json is essentially a text file with a different extension so I am guessing you might mean converting it to the current CAVS formats) but instead converts json to and from an internal C data structure representation. Then it is possible to call the correct functions to execute the cipher operations, after which the data structure is converted back into the correctly formatted json response. 

In CAVS parlance, the parser would take in a .req file, call the correct algorithms and get the results, and return a .rsp file. Except now the .req and .rsp file are in a different format. The parser is the test harness- it produces response vectors. If you send the vectors to the vendor to produce responses then you would not use the parser at all yourself (the vendor could use it).

**Comment by smuellerDD** [comment]
Am Donnerstag, 7. Februar 2019, 22:27:23 CET schrieb jramage77:

Hi jramage77,

> Hi - although I've reviewed the README file including the section on
> implementations, I have additional questions on how to add a new vendor
> module to Proxy. Being a lab, we typically we would use the CAVS tool to
> specify module algorithms/modes, generate and verify vectors then submit to
> CAVP.
> 
With ACVP, the proxy is intended to provide a replacement for that tool with 
the goal to keep managment simple.

> With the new ACVP server and the Proxy, how do we build and install a new
> vendor module implementation? I'm trying to fully understand this procedure
> so we can estimate time required to fully implement, test and submit vendor
> module algorithms.
> 
> Are these the steps?
> 
>   A - MODULE IMPLEMENTATION: - create a new C program for vendor module e.g.
> similar to "definition_impl_openssl.c" with cipher defs specification based
> on module capabilities

Correct.

The precise cipher option definitions are specified in the respective lib/
definition_cipher*.h.

For common cipher definitions, I prepared some helper macros provided in lib/
module_implementations/definition_impl_common.h.

For starters, you can and should mine the OpenSSL definitions by simply 
copying the respective sections and adjusting the options as needed and 
documented in the definition_cipher*.h files.
> 
>   B - MODULE DEFINITION: - create new module definitions directories:
> module_info, oe and vendor files.

Correct. As the cipher options are rather static, I kept them in C to also 
benefit from the compiler to help you with the data structure verification. 
The actual OE and module definitions however are subject to change and thus 
are maintained in these config files.
> 
>   C - Request vector sets for module implementation

Yes, using the the proxy.
> 
>   D - Obtain response vectors - use the Parser to convert json to from text
> (a la CAVS) and send to vendor for harness testing to produce response
> vectors

The parser will read the JSON files and parse the data into C data structures. 
The associated backend(s) then use the C data structures to invoke the IUT.

So, you would ship the JSON test vectors to your IUT. Then you ensure you have 
a oarser backend that links with your IUT and invoke the parser to read the 
JSON, invoke the IUT and unparse the response into the response JSON files.

Then you transport the response JSON files back to the proxy and tell it to 
upload it to the ACVP server to obtain the verdict.
> 
>   E - Verify response vectors and submit - ANY ADDITIONAL PROGRAMMING
> REQUIRED FOR NEW MODULE IMPLEMENTATION???

Well, yes. If you want to use my ACVP Parser, you need to have a backend that 
links the parser with the IUT. That linkage works with any type of IUT. For 
example, I use it not only with shared libraries, but also with the Linux 
kernel, Java code like BouncyCastle, C++ libraries or applications that are 
invoked to test things like OpenSSH, libreswan or strongswan.

See the backends/backend_openssl.c as an example.

The backends are intended to only invoke the API of the module. The backends 
are agnostic of any JSON parsing or any ACVP specific test procedure (like 
MCT).
> 
> Any additional insights and guidance would be appreciated.



Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, 7. Februar 2019, 23:23:36 CET schrieb Heidi Hart:

Hi Heidi,

> I am not an expert but I think I may be able to clarify a few things based
> on my own understanding:
> 
> I believe that the parser does not convert json to and from text (the json
> is essentially a text file with a different extension so I am guessing you
> might mean converting it to the current CAVS formats) but instead converts
> json to and from an internal C data structure representation. Then it is
> possible to call the correct functions to execute the cipher operations,
> after which the data structure is converted back into the correctly
> formatted json response.

That is fully correct.

To ease the transition for our clients, for example, I added an ACVP2CAVS and 
CAVS2ACVP backend which creates CAVS request files or reads CAVS response 
files.

> 
> In CAVS parlance, the parser would take in a .req file, call the correct
> algorithms and get the results, and return a .rsp file. Except now the .req
> and .rsp file are in a different format. The parser is the test harness- it
> produces response vectors. If you send the vectors to the vendor to produce
> responses then you would not use the parser at all yourself (the vendor
> could use it).

You nailed it :-)

Ciao
Stephan

**Comment by jramage77** [comment]
Heidi and Stephan - I appreciate both of your responses very much! I will proceed with a test vendor module implementation including setup with the parser and a mock IUT. 
Thank you for now!
James Ramage, DXC Technology, Ottawa/Canada.
