### ISSUE TITLE
Requesting sample response files

### ISSUE THREAD

**Issue by amrithathorath** [smuellerDD/acvpproxy#8]
I'm trying to run the command to retrieve sample resp files but see an error. And I've run this app before and don't remember having to update acvVersion.
```
 ./acvp-proxy -m "OpenSSL (64 bit) (SHA_AVX2)" --sample
...
...
ACVPProxy (15:50:54) Status: (Re)Try testID 1707
ACVPProxy (15:50:55) Error: Process following server response (ret: 0): {
  "acvVersion" : "0.4",
  "error" : "No Test Session with id of: (1707) was found"
}
ACVPProxy (15:50:55) Error: Failure in processing testID 1707 with vsID 0 (-111)
```

Next thing I wanted to check is how to request vectors for algs like GCM, KAS, KDFs. The "acvp-proxy -l" option lists SHA, AES, TDES. What if I need others?

**Comment by smuellerDD** [comment]
Am Freitag, 8. März 2019, 22:00:01 CET schrieb amy123:

Hi amy123,

> I'm trying to run the command to retrieve sample resp files but see an
> error. And I've run this app before and don't remember having to update
> acvVersion. ```
>  ./acvp-proxy -m "OpenSSL (64 bit) (SHA_AVX2)" --sample
> ...
> ...
> ACVPProxy (15:50:54) Status: (Re)Try testID 1707
> ACVPProxy (15:50:55) Error: Process following server response (ret: 0): {
>   "acvVersion" : "0.4",
>   "error" : "No Test Session with id of: (1707) was found"
> }
> ACVPProxy (15:50:55) Error: Failure in processing testID 1707 with vsID 0
> (-111) ```
> 
> Next thing I wanted to check is how to request vectors for algs like GCM,
> KAS, KDFs. The "acvp-proxy -l" option lists SHA, AES, TDES. What if I need
> others?

You can only get a sample with a request:

--sample --request

Ciao
Stephan

**Comment by amrithathorath** [comment]
Thanks for the response Stephan.
What modules do I use if I need to request DRBG, GCM, KAS, KDFs?

**Comment by smuellerDD** [comment]
Am Montag, 11. März 2019, 13:59:37 CET schrieb amy123:

Hi amy123,

> Thanks for the response Stephan.
> What modules do I use if I need to request DRBG, GCM, KAS, KDFs?

Depends: I sorted them into their dependencies. Hence, all AES-depending 
ciphers (GCM, CTR DRBG) are requested with AES modules and all SHA-based 
ciphers (other DRBGs, KAS, KDFs) are obtained with the hashing modules.

Ciao
Stephan

**Comment by amrithathorath** [comment]
Thanks...
