### ISSUE TITLE
Error logging into ACVP server

### ISSUE THREAD

**Issue by amrithathorath** [smuellerDD/acvpproxy#9]
I'm trying to request sample vectors and I'm seeing the following error.

```
amritha@thorath-vm:~/acvpproxy-master$ ./acvp-proxy -m "OpenSSL (64 bit) (SHA_AVX)" --sample --request
ACVPProxy (14:40:26) Status: Register module OpenSSL (64 bit) (SHA_AVX)
ACVPProxy (14:40:26) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (14:40:26) Status: Logging into ACVP server
ACVPProxy (14:40:28) Error: Process following server response: {
  "acvVersion" : "0.5",
  "error" : "The supplied one time password could not be verified"
}
ACVPProxy (14:40:28) Error: Failure to submit testID 0
```
I've run this successfully until last week and didn't have any issues. All certs are still the same.
Also, checked with NIST to see if my TOTP has to be regenerated and apparently its not changed so it should be good to use.
Any pointers why this might be happening?

**Comment by smuellerDD** [comment]
Usually this may be a time shift. I.e. Your time may be off from the server time.

Ciao
Stephan

**Comment by amrithathorath** [comment]
Okay thank you...

**Comment by amrithathorath** [comment]
I got past the previous issue I had with time not being in sync. But now I see the following error.

```
amritha@thorath-vm:~/acvpproxy-master$ ./acvp-proxy -m "OpenSSL (64 bit) (AESNI_CLMULNI)" --sample --request
ACVPProxy (10:17:35) Status: Register module OpenSSL (64 bit) (AESNI_CLMULNI)
ACVPProxy (10:17:35) Status - TOTP MQ System: Requesting OTP value, waiting ...
ACVPProxy (10:17:35) Status: Logging into ACVP server
ACVPProxy (10:17:36) Error: Process following server response: <html><head><title>JBWEB000065: HTTP Status 404 - </title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>JBWEB000065: HTTP Status 404 - </h1><HR size="1" noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</p><p><b>JBWEB000068: message</b> <u></u></p><p><b>JBWEB000069: description</b> <u>JBWEB000124: The requested resource is not available.</u></p><HR size="1" noshade="noshade"></body></html>
ACVPProxy (10:17:36) Error: Failure to submit testID 0
```

Do I need to get the latest version of code that supports v1.0 and would that fix the problem?

**Comment by smuellerDD** [comment]
Am Donnerstag, 18. April 2019, 16:42:58 CEST schrieb amy123:

Hi amy123,

> I got past the previous issue I had with time not being in sync. But now I
> see the following error.

Are you using the current git HEAD? If not, the issue is

https://github.com/usnistgov/ACVP/issues/606

There will be more hiccups coming in the near future considering 

https://github.com/usnistgov/ACVP/issues/633

At the moment since everything is in flux on the server side, there is no 
release that works with the current state.

You can only try to take the HEAD of the git repo.

Ciao
Stephan

**Comment by amrithathorath** [comment]
Thanks Stephan, that helps...

**Comment by smuellerDD** [comment]
With the current ACVP server and v0.7.0 of the ACVP proxy, the issues should be gone now.

**Comment by amrithathorath** [comment]
I've taken the latest code and trying to build it. I see the following error:

```
/usr/bin/ld: lib/openssl_thread_support.o: undefined reference to symbol 'CRYPTO_num_locks'
/home/amritha/ssl/lib/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
```
All my openssl and curl libraries are intact from previous tests. Also just ran the previous version of code and can build successfully.

**Comment by smuellerDD** [comment]
Am Freitag, 3. Mai 2019, 16:03:27 CEST schrieb amy123:

Hi amy123,

> I've taken the latest code and trying to build it. I see the following
> error:
> 
> ```
> /usr/bin/ld: lib/openssl_thread_support.o: undefined reference to symbol
> 'CRYPTO_num_locks' /home/amritha/ssl/lib/libcrypto.so.1.0.0: error adding
> symbols: DSO missing from command line ```
> All my openssl and curl libraries are intact from previous tests. Also just
> ran the previous version of code and can build successfully.

So you use OpenSSL 1.0.0? This is quite old and I am not sure whether the 
locking support was present in those old libraries.

I can only say for OpenSSL >= 1.0.1 that the locking is needed for 
multithreaded use cases.

That said, have you ever had random crashes with the acvp-proxy and your 
version of OpenSSL? If not, then probably the locking issue is only applicable 
for 1.0.0 < x < 1.1.0.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Freitag, 3. Mai 2019, 16:03:27 CEST schrieb amy123:

Hi amy123,

> I've taken the latest code and trying to build it. I see the following
> error:
> 
> ```
> /usr/bin/ld: lib/openssl_thread_support.o: undefined reference to symbol
> 'CRYPTO_num_locks' /home/amritha/ssl/lib/libcrypto.so.1.0.0: error adding
> symbols: DSO missing from command line ```
> All my openssl and curl libraries are intact from previous tests. Also just
> ran the previous version of code and can build successfully.

Looking into https://linux.die.net/man/3/crypto_num_locks I see that the API 
call is available since 0.9.4. So, it should definitely be present in your 
code.

Thus, can you please see in your binary why that API call is not present?

Ciao
Stephan

**Comment by amrithathorath** [comment]
I'm using openssl-1.0.2p not 1.0.0.
And no, I don't think I've ever encountered the crash scenario.
The thing is with the previous of version acvp-proxy I can still build it successfully but not with the latest version which is why I posted it here to check if I've missed out something.
Sure, I'll check if there's something wrong in the lib file generated.
Thanks again for being so patient with me...

**Comment by smuellerDD** [comment]
Am Freitag, 3. Mai 2019, 17:41:44 CEST schrieb amy123:

Hi amy123,

> I'm using openssl-1.0.2p not 1.0.0.
> And no, I don't think I've ever encountered the crash scenario.
> The thing is with the previous of version acvp-proxy I can still build it
> successfully but not with the latest version which is why I posted it here
> to check if I've missed out something. Sure, I'll check if there's
> something wrong in the lib file generated. Thanks again for being so
> patient with me...

Well, in order to get going, you can simply change:

#if OPENSSL_VERSION_NUMBER < 0x10100000L

to

#if 0

in openssl_thread_support.c

But please grep in your OpenSSL code whether the symbol is present in the 
source code. If it is, you may need to analyze why it is not in the binary. 
Not sure, but maybe there is a compilation option for OpenSSL to enable 
threaded support.

Yet it is strange that you did not encounter a crash. For me it constantly 
crashes on OpenSSL 1.0.x when the threading is ongoing due to races in OpenSSL 
without the code that was added.

Ciao
Stephan
